### ISSUE TITLE
Potentially using in a wasm target?

### ISSUE THREAD

**Issue by max-sixty** [zesterer/chumsky#111]
I'm hoping to allow a library to compile to a wasm target. We're using `pest-derive` at the moment, which I think doesn't support a wasm target

Would Chumsky? I see there's a `std` feature that can be turned off — would you have any thoughts on how much of Chumsky's features we can use without that feature? 

(for transparency, I'm a big fan of Chumsky, but was really hoping to not rewrite the parser quite yet, so I'll probably push it off for a while iff we can. Forgive the noise if so.)

ref https://github.com/max-sixty/prql/issues/175 & https://github.com/max-sixty/prql/issues/131

**Comment by zesterer** [comment]
Chumsky should definitely work without `std`! I think there are only a few minor features that don't work without the feature, and none of those should change the way you work with the crate. If you run into any issues, feel free to mention them and I'll be sure to fix them!

**Comment by max-sixty** [comment]
Great, thanks @zesterer!
