### ISSUE TITLE
Not able to use `text` functions

### ISSUE THREAD

**Issue by Vaimer9** [zesterer/chumsky#113]
The functions provided in the `text` modules which parse primitives do not work in latest release. I've taken this straight from the example:
```rs
// Asks for type annotations
// From `chumsky/tutorial.md`
let int = text::int(10)
            .map(|s: String| Tokens::Num(s.parse().unwrap()))
            .padded();

// Asks for type annotations as well
// From `chumsky/examples/nano_rust.rs`
let num = text::int(10)
        .chain::<char, _, _>(just('.').chain(text::digits(10)).or_not().flatten())
        .collect::<String>()
        .map(Tokens::Num);

// I have my `Tokens` struct set up alright for each of them to work, i.e separately
```
This may just be a stupid mistake on my end but just wanted to know why this was happening, thanks in advance!

**Comment by zesterer** [comment]
The parsers in `text` are generic across characters and will accept both `char` and `u8` input streams. You can tell the compiler which to use with `text::digits::<char, _>(10)`.  Hopefully this works!

**Comment by Vaimer9** [comment]
Thank you very much, is there some place where I can ask such questions without making issues? I reckon I'll encounter more of these problems 😅

**Comment by Vaimer9** [comment]
oh sry I'll just use the discussions tab to ask the question I have.
