### ISSUE TITLE
Make 'unwrapped' use track_caller

### ISSUE THREAD

**Issue by zesterer** [zesterer/chumsky#119]

**Comment by CraftSpider** [comment]
Playing around - Adding track_caller makes the default stack trace just ignore the unwrapped function. A way to get better errors would be to get the location and move it into the parser - which looks like it would require making unwrapped a custom combinator, but it would allow a nice "Parser defined at {} failed to unwrap. Error: {}"

**Comment by zesterer** [comment]
Yep, I found similar when investigating this myself. I suspect we'll want something similar to the `todo` parser.
