### ISSUE TITLE
`Simple` display should show `Debug` representations of input / expectations.

### ISSUE THREAD

**Issue by nathan-at-least** [zesterer/chumsky#131]
The `Display` impl for `Simple` shows raw output and expectations, which is awkward for whitespace, such as '\n':

Example:

```
use chumsky::primitive::{end, just};
use chumsky::Parser;

type Error = chumsky::error::Simple<char>;

fn main() {
    match parser().then_ignore(end()).parse("\nblah") {
        Ok(_) => panic!("Should not happen."),
        Err(es) => {
            for e in es {
                println!("{}", e);
            }
        }
    }
}

fn parser() -> impl Parser<char, (), Error = Error> {
    just("foo")
        .ignored()
        .or(just("\r\n").repeated().ignored())
        .or(just(' ').repeated().at_least(1).ignored())
}
```

-gives output:

```
found '
 was expectedend of input, f, 
```

Note also that sending raw whitespace (either inputs or expectations) behaves differently on different platforms and terminal types.

A `Debug`-style representation would be more useful for users, something like:

```
found '\n', was expecting 'f', '\r', or '\n'
```

**Comment by zesterer** [comment]
Good idea, I'll try to get this changed soon.

**Comment by zesterer** [comment]
Another issue I need to remember to fix: the impl currently erroneously displays a custom error as "found end of input".

**Comment by dark-fusion** [comment]
What is the current status of this issue?

If it has yet to be claimed, I'd be more than happy to work on this and submit a PR.

**Comment by zesterer** [comment]
A PR would be very welcome!

**Comment by dark-fusion** [comment]
Working on it. I should be able to put together a PR today. I'm very new to the codebase so if I come across anything out of the ordinary I'll let you know.
