### ISSUE TITLE
Suggested README readability optimization

### ISSUE THREAD

**Issue by mentalisttraceur** [zesterer/chumsky#132]
I suggest making the following formatting change to reduce mental parsing load on human readers:

```diff
-Chumsky provides a variety of recovery strategies (each implementing the `Strategy` trait), but it's important to understand that which you apply, where you apply them, and in what order will greatly affect the quality of the errors that Chumsky is able to produce, along with the extent to which it is able to recover a useful AST. Where possible, you should attempt more 'specific' recovery strategies first rather than those that mindlessly skip large swathes of the input.
+Chumsky provides a variety of recovery strategies (each implementing the `Strategy` trait), but it's important to understand that
+
+* which strategy you apply,
+* where you apply them, and
+* in what order you apply them
+
+will greatly affect the quality of the errors that Chumsky is able to produce, along with the extent to which it is able to recover a useful AST. Where possible, you should attempt more 'specific' recovery strategies first rather than those that mindlessly skip large swathes of the input.
```

That way the visual layout matches the semantic structure of "[...] it's important to understand that [list of factors] will greatly affect the quality [...]".

For me this sentence was long enough to require either working memory strain or skimming ahead to figure out the structure. Knowing the structure ahead-of-time helps with that, and encoding that in the text shape is a better fit for human vision.

(I'd make this as a PR but the overhead of fiddling with GitHub forks is too high for me right now.)

**Comment by zesterer** [comment]
Thanks for the suggestion! I've improved this in d41021.
