### ISSUE TITLE
Change `validate` callback to return `Result<U, Error>`.

### ISSUE THREAD

**Issue by nathan-at-least** [zesterer/chumsky#141]
I'm stretching `chumsky` in an admittedly unusual direction, but glossing over details (described more in
https://github.com/zesterer/chumsky/discussions/139#discussioncomment-2752671), I have run into a case where if [`chumsky::Parser::validate`](https://docs.rs/chumsky/0.8.0/chumsky/trait.Parser.html#method.validate) handled errors with a standard `Result` returned from `f` it would solve my case.

The signature that would solve my issue would look like this:

```rust
fn validate<F, U>(self, f: F) -> Validate<Self, O, F>
where
    Self: Sized,
    F: Fn(O, <Self::Error as Error<I>>::Span) -> Result<U, Self::Error>,
```

This seems "more natural" to me, as well as resolving my (admittedly unusual) issue. The reason it resolves my issue is that `U` is a type which has no value (ie: `enum Uninstantiatable {}` similar to [std](https://doc.rust-lang.org/std/index.html)::[convert](https://doc.rust-lang.org/std/convert/index.html)::[Infallible](https://doc.rust-lang.org/std/convert/enum.Infallible.html#)) and I always produce the error case. With the current API, there's no way to express the return value.

Is there some constraint that prevents my suggested interface (which I claim "feels more natural")?

 If `emit` is ever called, what happens to the returned `U` value in the current API? That also seems confusing.

**Comment by zesterer** [comment]
`validate` is intended for cases where you wish to produce an error, but where the output value is not inherently incorrect. An example might be an integer literal that's out of range, for example.

[`try_map`](https://docs.rs/chumsky/0.8.0/chumsky/trait.Parser.html#method.try_map) has a signature that, I believe, will some your problem.

**Comment by nathan-at-least** [comment]
Yes, `try_map` does exactly what I need, so disregard this ticket. Thanks!
