### ISSUE TITLE
Add example of `Label` improving error messages.

### ISSUE THREAD

**Issue by nathan-at-least** [zesterer/chumsky#146]
The doc-string for [`Parser::labelled`](https://docs.rs/chumsky/0.8.0/chumsky/trait.Parser.html#method.labelled) shows asserting that error values have a label, but I have not found a way for these to influence error output.

For example, I expect this code to say something about "expected just bar" or "expected ignored bar", but the error message just says expecting 'b'. I also tried feeding parse errors to the [`json` example](https://github.com/zesterer/chumsky/blob/master/examples/json.rs), after seeing it used `labelled`, but it also only produced low level next-character expectations in error messages.

How can I use labels to provide parser users high-level error messages, ie: "unexpected '%', expecting expression"?

```rust
use chumsky::prelude::*;

type Error = Simple<char>;

fn main() {
    if let Some(errors) = my_parser().parse("foo").err() {
        for (i, e) in errors.into_iter().enumerate() {
            println!("[{}]\n{}\n", i, e); 
        }   
    }   
}

fn my_parser() -> impl Parser<char, (), Error = Error> {
    just("bar")
        .labelled("just bar")
        .ignored()
        .labelled("ignored bar")
        .map_err(|e: Error| {
            assert!(e.label().is_some());
            e   
        })  
}
```

**Comment by zesterer** [comment]
The [`nano_rust`](https://github.com/zesterer/chumsky/blob/main/examples/nano_rust.rs) example now makes extensive use of `.labelled(...)` and we'll be writing docs for the labelling API ready for the release of 1.0, so I'm going to close this for now. Happy to re-open it if this still needs extra work down the line.
