### ISSUE TITLE
[Need help] the trait `Container<u8>` is not implemented for `String`

### ISSUE THREAD

**Issue by TornaxO7** [zesterer/chumsky#156]
Hello! I hope it's fine if I ask a question about a part of my code. It's in [this line](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L72).

### What should the parser be able to do?
I'm trying to implement a parser for [RFC 2047](https://datatracker.ietf.org/doc/html/rfc2047).
To be more specifique, I'm trying to implement the given context-free grammer which is shown in [section 2](https://datatracker.ietf.org/doc/html/rfc2047#section-2).

The parser should read the single bytes (so `u8` in rust) and parse them.

### What's the problem
As described in the title and in the first line, I'm getting the following error for example:

```rust
error[E0277]: the trait bound `String: Container<u8>` is not satisfied
  --> src/lexer.rs:73:10
   |
73 |         .ignore_then(charset)
   |          ^^^^^^^^^^^ the trait `Container<u8>` is not implemented for `String`
   |
   = help: the following implementations were found:
             <String as Container<char>>
             <&'a str as Container<char>>
   = note: required because of the requirements on the impl of `chumsky::Parser<u8, String>` for `Just<u8, String, _>`
```
which referring to [line 73](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L73) obviously.

I'm unsure what it means with
```rust
the trait `Container<u8>` is not implemented for `String`
```
and I don't really know, huwcould you help me here please?

**Comment by TornaxO7** [comment]
Wow, I think that I just found out what the error means.

```rust
just(EncodedWord::PREFIX)
```
Returns a "`String`" since `EncodedWord::PREFIX` is a String itself, so chumsky expects that the next expressions are gonna be strings as well which wasn't the case, they are `Container<u8>`.

So I just chanked `Encoded::PREFIX` into a `[u8]` and now it's working :)

**Comment by zesterer** [comment]
Good to hear you solved this!

**Comment by TornaxO7** [comment]
Thank you for your very quick response! c(^-^)c
