### ISSUE TITLE
Simple parser without map

### ISSUE THREAD

**Issue by natemartinsf** [zesterer/chumsky#16]
I'm trying to define a simple parser that will ignore whitespace (which is already tokenized by my lexer.)

`    let whitespace = just(WHITESPACE).or_not().ignored();
`

This is the error I get:

> 63 |     let whitespace = just(WHITESPACE).or_not().ignored();
>    |         ----------   ^^^^ cannot infer type for type parameter `E` declared on the function `just`
>    |         |
>    |         consider giving `whitespace` the explicit type `To<OrNot<Just<Token<'_>, E>>, Option<Token<'_>>, ()>`, where the type parameter `E` is specified

That's a lot of boilerplate to add for a simple parser. Am I doing something incorrectly here?

**Comment by oOBoomberOo** [comment]
The parsers are generic across Error type so you have to specify a concrete type at some point.

for example, I can hint to the compiler that I want the error type to be `nom::error::Simple<char>` by using turbofish syntax in `just()`
```rust
let whitespace = just::<_, Simple<char>>(WHITESPACE).or_not().ignored();
```
or you can also let rust infer it from the function's return signature but this need more context about your code to be type out fully.
```
fn foo_parser() -> impl Parser<char, ???, Error = Simple<char>> {
  just(WHITESPACE).or_not().ignored()
}
```

**Comment by zesterer** [comment]
@oOBoomberOo's answer is correct.

In general, you only need to specify the error type once within a parser and Rust will correctly infer it for the rest of the combinators. It's a bit of a shame that there isn't a better way to give Rust this information though. I'm almost tempted to add a `.with_error::<E>()` combinator that does nothing except providing the compiler with the information it needs to infer the correct type elsewhere.

The better solution, as mentioned, is to mention the error type as part of the function signature. [In Tao, I even use a type alias to make things a bit simpler](https://github.com/zesterer/tao/blob/tao2/syntax/src/parse.rs#L3).

**Comment by natemartinsf** [comment]
Fantastic, thank you! I'm fairly new to rust, so I didn't know that you could give the type hint without specifying all of the generics.

Thank you for this crate, and thank you for bringing it back to my attention on Reddit! I'm really enjoying using it.
