### ISSUE TITLE
[Question] "Repeated parser iteration succeeded but consumed no inputs"

### ISSUE THREAD

**Issue by TornaxO7** [zesterer/chumsky#164]
## Introduction
Hello! I'm sorry that I'm asking you that much at the moment. This problem here might be a little bit to "specifique" because I'd like to get some help for my code, so feel free to deny this question if it's too much for you.

## The error message
I'm getting the following error message, if I run [my test][test]:
```rust
thread 'lexer::tests::test_clear_text' panicked at 'Repeated parser iteration succeeded but consumed no inputs
(i.e: continuing iteration would likely lead to an infinite loop, if the parser is pure).
This is likely indicative of a parser bug. Consider using a more specific error recovery strategy.',

/home/tornax/.cargo/registry/src/github.com-1ecc6299db9ec823/chumsky-0.8.0/src/combinator.rs:455:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(I reformatted the error output for better readability here)

## What I'm trying to parse
I'm triyng to parse `encoded words` which is specified in [RFC 2047][rfc]. [Here's the context-free-grammar-description][context-free-grammar] if you need it.

## Understanding of the code
The main-entrance of the whole module is the [`run`][run] function.

[`get_parser`][get_parser]
should give me the parser which should parse a given text and I assume that the
issue, which throws the error which I showed above, seems to be the following
[code-block][code-block]:
```rust
    encoded_word_parser.or(clear_text_parser)
            .repeated()
            .collect::<Tokens>()
```

Because if I change my function [`get_parser`][get_parser] from:
```rust
fn get_parser() -> impl Parser<u8, Tokens, Error = Simple<u8>> {
    use chumsky::prelude::*;

    let clear_text_parser = get_clear_text_parser();
    let encoded_word_parser = get_encoded_word_parser();

    encoded_word_parser.or(clear_text_parser)
        .repeated()
        .collect::<Tokens>()
}
```
to
```rust
fn get_parser() -> impl Parser<u8, Token, Error = Simple<u8>> {
    use chumsky::prelude::*;

    let clear_text_parser = get_clear_text_parser();
    let encoded_word_parser = get_encoded_word_parser();

    encoded_word_parser
        .or(clear_text_parser)
}
```

everything works fine, I just need to adjust the tests to expect a _single_
token except a vector of tokens, but I'd like to parse a string which could have
multiple encoded words in a string.

Here's an image of the diff, so you can see the changes better:

<details>

![image](https://user-images.githubusercontent.com/50843046/176493787-8fb8d9f9-d79f-49d5-ba57-47d510d52575.png)

</details>

Do you have an idea what I'm doing wrong and what I could do to fix that?

[test]: https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L145
[get_parser]: https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L81
[run]: https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L75
[rfc]: https://datatracker.ietf.org/doc/html/rfc2047.
[context-free-grammar]: https://datatracker.ietf.org/doc/html/rfc2047#section-2
[code-block]: https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L87

**Comment by CraftSpider** [comment]
`repeated` accepts any number of items, with a significant note that that _includes zero_. Your `clear_text_parser` also includes a `repeated` at the top level, so it can match empty as a valid input. One simple fix is to add `at_least(1)` after repeated call in `get_clear_text_parser`, which will causes it to fail on empty inputs.

**Comment by TornaxO7** [comment]
Ah thank you for the explanation and thank you for your answer :) I hope it didn't took you too long to understand my code :sweat_smile:
