### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [zesterer/chumsky#171]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@w-henderson) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by zesterer** [comment]
Hi,

You can contact me via my email address, which I list publicly on my GitHub profile.

I'll make adding a `SECURITY.md` part of my todo list.

**Comment by JamieSlome** [comment]
@zesterer - thanks for your diligence ⚡ 

In the meantime, feel free to view the report here:
https://huntr.dev/bounties/17f2765f-8782-4510-ae46-2c30090bb4ec/

It is private and only accessible to you 👍

**Comment by zesterer** [comment]
With respect, I'd appreciate it if you could email information about this to me rather than using a third-party service.

**Comment by JamieSlome** [comment]
@zesterer - just sent you an e-mail 👍
