### ISSUE TITLE
[Question] Implement grammar

### ISSUE THREAD

**Issue by TornaxO7** [zesterer/chumsky#172]
## Disclaimer
Hello! This question might be probably a little to specifique so feel free to deny my question if you don't want to spend too much time with it.

## The problem
I have the following context-free grammar:
```
G = (
    N = {A, B},
    T = {'a', 'b', ε},
    S = A,
    P = {
        A = aB | aA | ε,
        B = bA | bB,
    }
)
```
and I'd like to write a parser for it now.

The only way to implement the parser, which I got in my mind, was something like this:
```rust
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Expr {
    Char(char)
}

fn main() {
}

fn get_parser() -> impl Parser<char, Expr, Error = Simple<char>> {
    // ...
}
```

and then using the
[`recursive`](https://docs.rs/chumsky/0.8.0/chumsky/recursive/fn.recursive.html)
function which would only collect one char, put in `Expr::Char` and returns it.

As you might see, this isn't a good implementation-idea for this kind of parser.
I was thinking about collecting the first `a`'s in a `Vec<char>` as long as
possible until the parser reaches a `b` to switch to the other production rule
(here it's `B`) but I couldn't find a suitable implementation for that.

Do you have any tips or suggestions how I could implement the parser for this?

**Comment by zesterer** [comment]
Have you taken a look at the [tutorial](https://github.com/zesterer/chumsky/blob/master/tutorial.md)? I feel like it gives a good overview of how best to structure more complex chumsky parsers. There are enough similarities with your syntax that you might even be able to just adapt the tutorial's code!

**Comment by TornaxO7** [comment]
> Have you taken a look at the [tutorial](https://github.com/zesterer/chumsky/blob/master/tutorial.md)?

Yes I did

> There are enough similarities with your syntax that you might even be able to just adapt the tutorial's code!

Hm.... ok, then I'll try it again.
