### ISSUE TITLE
[Need help/Question] Repeated parser iteration succeeded but consumed no inputs

### ISSUE THREAD

**Issue by TornaxO7** [zesterer/chumsky#173]
## Disclaimer
Hello, it's me again! I'm sorry that I'm often asking for help but I hope that it's fine... as I already said, you are always free to say that you don't want to get any questions like that again.

## The problem
I'm getting the following error message:
```rust
thread 'lexer::tests::test_encoded_from_1'
panicked at 'Repeated parser iteration succeeded but consumed no inputs
(i.e: continuing iteration would likely lead to an infinite loop, if the parser is pure).
This is likely indicative of a parser bug.
Consider using a more specific error recovery strategy.',
```

(formatted for better readability)

if I run `cargo test` on my
[fork](https://github.com/TornaxO7/rfc2047-decoder/tree/7_lexer_using_chumsky).

If you remember, I've already asked a [similar
question](https://github.com/zesterer/chumsky/issues/164). I was trying to find
the issue but I can't find a fix.

## Where to start
[This](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L81)
function returns the parser for the program.

## What have you tried?
- I changed [this
line](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L101)
to
```rust
any().repeated().at_least(1).at_most(1).map(|value: Vec<u8>| Token::ClearText(value[0]))
```
but that doesn't work
- I also took a look into the [`encoded-
word-parser`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L104)
but I couldn't see anything which I could fix there.

I'd be happy if anyone can help me here :)

**Comment by zesterer** [comment]
[Here](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L84), you use `whitespace().repeated()` but the [`whitespace`](https://docs.rs/chumsky/latest/chumsky/text/fn.whitespace.html) parser already accepts any number of whitespace characters, so `whitespace().repeated()` can accept no inputs, spinning round indefinitely. I recommend removing the `.repeated()`.

**Comment by TornaxO7** [comment]
Thank you :)

**Comment by zesterer** [comment]
Does this not work as-is? `whitespace()` will consume any amount of whitespace characters.

**Comment by TornaxO7** [comment]
Oh god... I just found out that it was another issue... sorry! Yes you're right, it consumes any amount of whitespace :)
