### ISSUE TITLE
[Question] How to do `take_until` with `end`

### ISSUE THREAD

**Issue by TornaxO7** [zesterer/chumsky#175]
Hello! I'm trying to use [`take_until`](https://docs.rs/chumsky/0.8.0/chumsky/primitive/fn.take_until.html) to collect some bytes unless the parser inside `take_until` catches a pattern or it reaches the end.

Here is an an example what I mean:
```rust
take_until(just("="))
    .map(|(chars,  _): (Vec<char>, _)| Token::Chars(chars))
```
now it could happen, that I have a string like this one:
```
aaaaaaa
```

which dosen't have a `=` so it wouldn't collect those `a`'s. I've tried to do `take_until(just("=").or(end())` but since the `just("=")` and `end()` parser don't return the same thing (and `end()` just returns `()`), I'm not able to do this.

Do you have an idea how I can those `a`'s until the parser reached a `=` or the end?

**Comment by zesterer** [comment]
You can make them produce the same thing using `.ignored()`, like so:

```rust
take_until(just("=").ignored().or(end()))
    .map(|(chars,  _): (Vec<char>, _)| Token::Chars(chars))
```

**Comment by TornaxO7** [comment]
I tried that as well as you can see [`here`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L101) but this gives me 
```
'Repeated parser iteration succeeded but consumed no inputs (...)
```
;-;

**Comment by zesterer** [comment]
What's the wider context of your code? This sounds like you have a second issue elsewhere.

**Comment by TornaxO7** [comment]
Ok, the bigger context:

I want to parse strings like those: `"this is clear text =?uft-8?B?this not?="`, `"hello =?utf-8?B?there?="`

The "main" parser, which should parse this string comes from [`get_parser`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L81). The parser for the encoded things (for this `=?<charset>?<encoding>?<encoded-text>`) comes from [`encoded_word_parser()`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L105). Now my problem comes from the [`clear_text_parser`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L98), which should try to collect all next bytes until it reaches the end of the string or an encoded_word as you can see [here](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L101) and the parser in `take_until` seems to be the issue.

**Comment by zesterer** [comment]
I'm not really sure I have enough information to provide a solution. What I would say is that if you run into problems, a solid strategy is to comment out unused parsers and minimise the problem until you've got something that's easier to fix.

**Comment by TornaxO7** [comment]
Ok, I think that I've found the issue. The problem is this [`.repeated()`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L95) in combination with [this `take_until`](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L101).

Here's a simplified version of my problem:
```rust
use chumsky::{prelude::Simple, Parser};

fn main() {
    let message = "aaaba";
    let parsed = get_parser().parse(message);
    println!("{:?}", parsed);
}

fn get_parser() -> impl Parser<char, Vec<char>, Error = Simple<char>> {
    use chumsky::prelude::*;

    let b = just("b");
    take_until(b.rewind().ignored().or(end()))
        .map(|(values, _): (Vec<char>, _)| values)
        .repeated()
        .flatten()
}
```

**Comment by TornaxO7** [comment]
Is it better for you to understand it now @zesterer ?

**Comment by zesterer** [comment]
It sounds like you want something akin to `.at_least(1)` on the `take_until`. That doesn't exist yet, so for now you could use a `.try_map` that emits an error if less than 1 character was found.

**Comment by TornaxO7** [comment]
> so for now you could use a .try_map that emits an error if less than 1 character was found.

could you please give me an example what you mean with this?
Do you mean it like this?
```rust
     take_until(b.rewind().ignored().or(end()))
        .try_map(|(values, ()): (Vec<char>, ()), _| Ok(values))
```

**Comment by lightningyx** [comment]
There is an example in the docs:
https://docs.rs/chumsky/latest/chumsky/trait.Parser.html#method.try_map

**Comment by zesterer** [comment]
Something like this should work:

```rust
.try_map(|(value, _)| if values.is_empty() { Err(...) } else { Ok(values) })
```

**Comment by TornaxO7** [comment]
Eh, I'm sorry but I don't really understand what you're trying to exlain me with `try_map`. How should `try_map` help me here to convert `aabbaaa` to `[[[a, a], [b, b], [a, a, a]]`?

**Comment by zesterer** [comment]
The problem right now is that `take_until(b.rewind()...)` accepts no characters, because it's fine for it to accept nothing before a `b`, and then revert even the `b`. You need to force `take_until` to only accept sequences of length >= 1, and using `try_map` after it allows you to do that.

**Comment by TornaxO7** [comment]
> The problem right now is that take_until(b.rewind()...) accepts no characters, because it's fine for it to accept nothing before a b, and then revert even the b.

Ooooh, now I got it! Thank you for pointing this out!

> You need to force take_until to only accept sequences of length >= 1, and using try_map after it allows you to do that.

thank you for the explanation :)

It's working now! Thank you guys!
If anyone is interested in the final code:

<details>

```rust
use chumsky::{prelude::Simple, Parser, error::SimpleReason};

fn main() {
    let message = "aaaba";
    let parsed = get_parser().parse(message);
    println!("{:?}", parsed);
}

fn get_parser() -> impl Parser<char, Vec<Vec<char>>, Error = Simple<char>> {
    use chumsky::prelude::*;

    get_a_collector()
        .or(get_b_collector())
        .repeated()
}

fn get_a_collector() -> impl Parser<char, Vec<char>, Error = Simple<char>> {
    use chumsky::prelude::*;

    let b = just("b");
    take_until(b.rewind().ignored().or(end()))
        .try_map(|(values, ()), span| if values.is_empty() { Err(Simple::custom(span, "yeet")) } else {Ok(values)})
}

fn get_b_collector() -> impl Parser<char, Vec<char>, Error = Simple<char>> {
    use chumsky::prelude::*;

    let a = just("a");

    take_until(a.rewind().ignored().or(end()))
        .try_map(|(values, ()), span| if values.is_empty() { Err(Simple::custom(span, "yeet")) } else {Ok(values)})
}
```

</details>

**Comment by TornaxO7** [comment]
Just a little question so I can be sure that I understood the problem. So the `Err` in
```rust
.try_map(|(values, _)| if values.is_empty() { Err(...) } else { Ok(values) })
                                               ^
                                           This `Err`
```
handles the case that it's trying to rewind "nothing" according to the line above it:
```rust
take_until(b.rewind().ignored().or(end()))
               ^
           This one
```
am I right?

**Comment by zesterer** [comment]
The `Err` handles the case in which `take_until` consumes no tokens before the terminating pattern.

**Comment by TornaxO7** [comment]
oh ok

**Comment by TornaxO7** [comment]
Thank you for being so responsive c(^-^)c
