### ISSUE TITLE
`at_least` for only one primitive of `or` combinator

### ISSUE THREAD

**Issue by SpriteOvO** [zesterer/chumsky#177]
Suppose the input is:

```
A B A B A A B
```

where `A` and `B` are unordered.

Parser pseudo-code (I did not verify it):

```rust
just('A').or(just('B')).padded().repeated()
```

Is there a way to only require `B` to appear at least once?

```
# allows
A A B A
B B B
B

# disallows
A A A
```

Thanks in advance!

**Comment by zesterer** [comment]
Does `just('A').repeated().then(just('B')).then(just('A').repeated())` not work?

**Comment by SpriteOvO** [comment]
> Does `just('A').repeated().then(just('B')).then(just('A').repeated())` not work?

@zesterer It does not seem to work.

It allows `B` to appear only once, not at least once. I tried adding `.repeated().at_least(1)` to the end of `just('B')`, but it still cannot match the `A` `B` inputs in random order. For example, the input is `AAABABAA`.

**Comment by zesterer** [comment]
Ah, right. 'At least once' is a context-sensitive rule (the parser needs to 'know' whether a `B` has already been seen), which is something that falls somewhat outside the scope of chumsky. That said, you can probably achieve something that fits your use-case like so:

```rust
just('A').or(just('B'))
    .repeated()
    .try_map(|xs| if xs.iter().filter(|c| *c == 'A').count() >= 1 {
        Ok(xs)
    } else {
        Err(...)
    })
```

**Comment by SpriteOvO** [comment]
@zesterer It works. Initially my attempt was `if b.len() < 1 { panic!() }`, I didn't realize there was `try_map` and `Simple::custom` functions. Thank you! :smile:
