### ISSUE TITLE
How do you parse a string containing escapes?

### ISSUE THREAD

**Issue by kevinbarabash** [zesterer/chumsky#178]
I'm using the following code from nano_rust.rs:
```
    // A parser for strings
    let str_ = just('"')
        .ignore_then(filter(|c| *c != '"').repeated())
        .then_ignore(just('"'))
        .collect::<String>()
        .map(Token::Str);
```
and then calling `snailquote::unescape()` on the result.

The problem I'm running into is that this doesn't work with the double quote escape.  The filter needs to know about the previous character.  I tried updating the closure to capture a variable but `filter` expects `Fn` instead of `FnMut`.

Here's what my code currently looks like:
```
    let mut is_prev_char_esc = false;
    let r#str = just("\"")
        .ignore_then(filter(move |c| -> bool {
            if is_prev_char_esc {
                is_prev_char_esc = false;
                true 
            } else if *c == '\\' {
                is_prev_char_esc = true;
                true
            } else {
                *c != '"'
            }
        }).repeated()
        .then_ignore(just("\""))
        .collect::<String>()
        .map_with_span(|value, span| {
            let value = unescape(&value).unwrap();
            Expr::Lit(Lit::str(value, span))
        });
```

**Comment by zesterer** [comment]
Have you taken a look at the JSON example? It's standard-compliant, and so includes string escaping. You might find it more useful than `nano_rust`!

**Comment by kevinbarabash** [comment]
```
filter(|c| *c != '\\' && *c != '"').or(escape)
```
That's just what I was looking for.  Thank you!
