### ISSUE TITLE
"Recursive" isn't compatible with "map_with_span"

### ISSUE THREAD

**Issue by natemartinsf** [zesterer/chumsky#18]
If you create a recursive parser that uses `map_with_span` to emit a tuple (T, span), you get the following error:

> 81 |     let expr = recursive(|expr| {
>    |                ^^^^^^^^^ expected enum `Expr`, found tuple
>    | 

I found a workaround by emitting just a single value with `.map(|x| x.0)`

I'm not sure if I'm doing something wrong here, or if this is just a limitation.

**Comment by zesterer** [comment]
Could you post more of the code? There should be no such limitation, but the recursive parser's output type and the output of the recursive element it gives you must match. Alternatively, you can pull the `map_with_span` outside of the `recursive` call to have it be applied afterwards.

**Comment by natemartinsf** [comment]
Sure, here's a more complete snippet:

https://gist.github.com/natemartinsf/c98ef7caa8ddbffda70a396eebf980e8

**Comment by zesterer** [comment]
I presume that `Spanned<T>` is similar to the one I use in `nano_rust.rs` (i.e: it's type alias of a tuple).

I generally add my `map_with_span`s at the end of the parser so that I can ignore the span for most of the parser, although it's really up to you. I've reworked your snippet a little, hopefully this works for you.

```rust
fn expr_parser<'a>() -> impl Parser<Token<'a>, Spanned<Expr>, Error = Simple<Token<'a>>> + Clone {
    let expr = recursive(|expr| {
        let ident = filter_map({
            |span, tok| match tok {
                IDENT(v) => Ok(Ident(v.to_string())),
                _ => Err(Simple::expected_input_found(span, Vec::new(), Some(tok))),
            }
        })
        .labelled("ident");

        let number = filter_map({
            |span, tok| match tok {
                NUMBER(v) => Ok(Number(v.to_string())),
                _ => Err(Simple::expected_input_found(span, Vec::new(), Some(tok))),
            }
        })
        .labelled("number");

        let atom = ident
            .map(Expr::Ident)
            .or(number.map(Expr::Number))
            .labelled("atom");

      
        atom
            .map_with_span(|expr, span| (expr, span))
    });

    expr
}
```

**Comment by natemartinsf** [comment]
Fantastic, that worked as expected!

On a side note, can you point me to any documentation on the syntax you're using for the map, with no parameters in the closure? (like .map(Expr::Number))

**Comment by zesterer** [comment]
When you create an enum like...

```rs
enum MyEnum {
    Foo(i32),
}
```

...`MyEnum::Foo` is implicitly a `fn(i32) -> MyEnum` and so it can be substituted into a `map` provided the arguments match! No extra syntax, just Rust generalising concepts like enum construction.

See [this SO post](https://stackoverflow.com/questions/54802045/what-is-this-strange-syntax-where-an-enum-variant-is-used-as-a-function).
