### ISSUE TITLE
Implement Parser for ! (never)

### ISSUE THREAD

**Issue by zesterer** [zesterer/chumsky#182]
This will allow the use of `todo!()` in places that expect a parser.

**Comment by msrd0** [comment]
I don't see how this would replace your existing parser? `todo!()` panics as soon as it's being called, i.e. when constructing the parser, while your `todo` parser (if I understood it correctly) only panics when it's used to parse something, not when it's being constructed.

**Comment by zesterer** [comment]
This is true, it wouldn't be a substitute. It would be nice to have it just compile though. Thanks for pointing this out!

**Comment by dvdvgt** [comment]
Hi! I really enjoyed using chumsky. I found the documentation really helpful, especially the tutorial on creating a little programming language. Thus, I'd like to contribute to this project. May I take this issue on? Is it still relevant?

**Comment by zesterer** [comment]
Yes, this would be a good thing to implement in `zero-copy` rather than `master`. One problem is that in `zero-copy`, the output type is an associated type which might preclude implementing this.

**Comment by zesterer** [comment]
`zero-copy` no longer has associated output types, so this should be possible (behind a nightly feature flag, of course).

**Comment by CraftSpider** [comment]
Kind of sad that basically this alone prevents output from being associated - OTOH, I don't see a better option without language support. I've had at least one impl that would have been allowed with associated types that I couldn't write, but ah well.

**Comment by zesterer** [comment]
Closing since #294 implemented this.
