### ISSUE TITLE
Implement a configurable integer/numeric parser

### ISSUE THREAD

**Issue by Lokathor** [zesterer/chumsky#184]
eg: `4_567` would be able to be parsed by `int_`

**Comment by zesterer** [comment]
Maybe I should just go the whole hog and write a fully-featured integer parser that can handle underscores, hex/oct/binary notation, etc. with configurable switches for everything, then configuration aliases for common configurations like C-style, Rust-style, etc. Probably not too hard to do for integers alone!

**Comment by zesterer** [comment]
Fwiw, for now you could just use:

```rs
let int_with_underscores = text::digit(10) // A digit...
    .repeated() // ...repeated multiple times, but
    .at_least(1) /// at least one time...
    .separated_by(just('_')) // ...in a list, separated underscores...
    .at_least(1) // ...with at least one element in that list
    .flatten()
    .collect::<String>();
```

**Comment by Lokathor** [comment]
But, also, can it not allocate somehow?

**Comment by zesterer** [comment]
Unfortunately not, for now. #82 will overhaul a lot of the internals and allow, among many other things, complex parsers like this to work entirely without allocations.

**Comment by Zij-IT** [comment]
Is this one overshadowed by #398, or completed via #462?

**Comment by zesterer** [comment]
I think that #462 pretty much resolves this one.
