### ISSUE TITLE
request: ignore_until primitive

### ISSUE THREAD

**Issue by Lokathor** [zesterer/chumsky#189]
It looks like if you use take_until(  ).ignored() the actual taking still makes a vec internally, it just throws it away after filling it up.

but heck maybe this is already done in zero-copy i dunno

**Comment by zesterer** [comment]
An idea I had recently was to generalise a lot of these "pull tokens until x" patterns with an [`and_is` and `not` combinator](https://github.com/zesterer/chumsky/issues/181#issuecomment-1207469482). In such a formulation, you'd just do:

```rs
x.not().ignored().repeated().then(x)
```

It's a bit wordier, but it IMO it generalises to more cases and the common ones can always be wrapped up in a more ergonomic combinator. I will take this onboard and do a bit of thinking read for `zero-copy`.

**Comment by zesterer** [comment]
`not` has now been implemented.
