### ISSUE TITLE
request (breaking): provide additional Span impls

### ISSUE THREAD

**Issue by Lokathor** [zesterer/chumsky#191]
`Span` is provided for `core::ops::Range`, but it would be good if it was also provided for the other range types in `core::ops` as well. It looks like this can't be done with the current `Span` interface, but maybe a future version of `Span` building on the `RangeBounds` trait could make this happen.

**Comment by zesterer** [comment]
I'm not sure how it would be possible to represent a span with anything other than `Range`. `RangeFrom`, for example, takes only a starting index and is not capable of representing arbitrary spans within source code (which is one of the intended goals of the `Span` trait).

**Comment by Lokathor** [comment]
Oh this issue, this issue is ancient! impossibly old! I wrote this issue before you explained what the `eoi` really does.
