### ISSUE TITLE
Stateful combinators

### ISSUE THREAD

**Issue by kevinbarabash** [zesterer/chumsky#195]
I'd like to give each of the nodes generated by my parser a unique ID.  ~Unfortunately, `map_to_span` takes a `Fn` instead of a `FnMut` so it looks like this isn't possible at the moment.  Is that correct?~ It looks like the issue was something else.  I was trying to use a `mut u32` to set a unique ID on each node, but I ran into the following error message:
```
`std::clone::Clone` is implemented for `&u32`, but not for `&mut u32`
```
See below for more details.

**Comment by Zij-IT** [comment]
Are you able to provide a code example of what you are trying to do?

**Comment by kevinbarabash** [comment]
I wanted something like the following:
```
fn parser() -> impl Parser<char, Json, Error = Simple<char>> {
    let mut id: u32 = 0;

    recursive(|value| {
        ...
    
         just("true")
                .map(|_| {
                    let node = Json::Bool(true, id);
                    id += 1;
                    node
                })
                .labelled("true"))
   })
}
```
I tried making a smaller parser in an attempt to reproduce the issue using a simpler piece of code, but I can't reproduce the issue with the simpler code.

**Comment by kevinbarabash** [comment]
Here's the error message I get from the parser I'm working on when I try the same thing there:
```
`std::clone::Clone` is implemented for `&u32`, but not for `&mut u32`
required because it appears within the type `[closure@crates/crochet_parser/src/expr.rs:153:28: 162:14]`
required because of the requirements on the impl of `std::clone::Clone` for 
`chumsky::combinator::MapWithSpan<chumsky::combinator::Then<chumsky::combinator::Map<
chumsky::combinator::Then<chumsky::BoxedParser<'_, char, &str, 
chumsky::error::Simple<char>>, chumsky::recursive::Recursive<'_, char, 
crochet_ast::Expr, chumsky::error::Simple<char>>>, fn((&str, 
...
// followed by many more lines of the same
```

**Comment by Zij-IT** [comment]
I believe to get the behavior you are after, you would have to add `move` before the closure definition, so that it knows to take `id` similar to `std::iter::from_fn`.

I believe the bound on `F` for `map_with_span` would have to be expanded to `FnMut` in order for your case to work. 

When `zero_copy` is done, it will feature a `map_with_state` function, so you would be able to store that in the state.

**Comment by zesterer** [comment]
You will require internal mutability, unfortunately. Parser functions are currently just `impl Fn(...)`, and so don't permit mutating their environment. You should be able to do this, however:

```rust
fn parser() -> impl Parser<char, Json, Error = Simple<char>> {
    let mut id = std::cell::Cell::new(0);

    recursive(|value| {
        ...
    
         just("true")
                .map(|_| {
                    let node = Json::Bool(true, id);
                    id.update(|id| id + 1);
                    node
                })
                .labelled("true"))
   })
}
```

**Comment by TzviPM** [comment]
I have another use case for stateful combinators, which is constructing de bruijn indices during parsing of an untyped lambda calculus. I am basing a parser on the book `Types and Programming Languages` by Pierce, 2002.

My current approach is to construct an ast with an `info` type containing spans and then construct de bruijn indices in a second pass over the ast.

If I were writing a recursive descent parser by hand, I'd like to store and pass around a context through which I could push/pop variable names and look up their indices while constructing an AST.

The disadvantage of simply adding a state generic type to a parser and allowing stateful combinators is that certain regular subgrammars that could be parallelized a la simd_json may also lose that ability when state is involved.

Thus it will be important to consider the trade-off between the optimizations that each of these scenarios allow for.

My suggestion, in light of this, would be to allow a `StatefulParser` trait that extends `Parser` with the ability to track state, and then `impl Into<StatefulParser<...>> for T where T: Parser<...>`

Is this something that chumsky would consider supporting? Is there a simpler way to do this that I'm missing?

**Comment by zesterer** [comment]
The `zero-copy` branch (a near-total rewrite of chumsky) includes state type parameters on all parsers, and a `map_with_state` combinator that allows accessing it during parsing. Your use-case is interesting though: tracking nesting during parsing. It'll have to do some thinking about exactly how we can ergonomically facilitate this.

**Comment by zesterer** [comment]
Going to close this in anticipation of #82, which implements this.
