### ISSUE TITLE
"dead end" Recovery Strategy for malformed binary and hexadecimal literals?

### ISSUE THREAD

**Issue by fmckeogh** [zesterer/chumsky#204]
To avoid an XY-problem, the problem I'm trying to solve is my Sail language lexer is failing to produce an error for malformed binary and hexadecimal values. For example the literal `0b2` should fail to parse with an error saying that it expected a `0` or a `1` after `0b`. Instead it is successfully parsed as a `Number(0)` and `Identifier(b2)` tokens, despite trying many different combinations of orderings in the top level `choice`.

I wrote a `DeadEnd` strategy:

```
/// Recovery strategy for unrecoverable inputs
pub(crate) struct DeadEnd;

#[allow(deprecated)]
impl<I: Clone + PartialEq, O, E: Error<I>> Strategy<I, O, E> for DeadEnd {
    fn recover<D: Debugger, P: chumsky::Parser<I, O, Error = E>>(
        &self,
        recovered_errors: Vec<Located<I, P::Error>>,
        fatal_error: Located<I, P::Error>,
        _parser: P,
        _debugger: &mut D,
        _stream: &mut Stream<'_, I, <P::Error as Error<I>>::Span>,
    ) -> (
        Vec<Located<I, P::Error>>,
        Result<(O, Option<Located<I, P::Error>>), Located<I, P::Error>>,
    ) {
        (recovered_errors, Err(fatal_error))
    }
}
```

with the intention of adding it to only the hex and bin lexers, so if an error occurs after seeing a `0b` then it is printed rather than recovered from, but this does not work and it still produces the `Number(0)` and `Identifier(b2)` tokens.

Full source here: https://github.com/fmckeogh/borealis/blob/51fa2df198436b0afdb56598618d8b6ce9b9a969/sail/src/lexer.rs

What am I doing wrong here? Thank you!

**Comment by zesterer** [comment]
I suspect that a better approach for you would to just use the [`validate`](https://docs.rs/chumsky/latest/chumsky/trait.Parser.html#method.validate) combinator rather than implementing a new recovery strategy. You can allow `0b<any number of numbers of letters>` to parse, and then use `validate` afterwards to check that they match the radix prefix afterwards, generating an error if they don't.

**Comment by fmckeogh** [comment]
@zesterer Thank you so much, I'll do that:)
