### ISSUE TITLE
Interdependant parsers

### ISSUE THREAD

**Issue by ClementNerma** [zesterer/chumsky#213]
Hi there!

I'm currently using this library for a project of mine, and have been struggling for a simple thing:

I have a parser in the form of a function called `statement`. It is declared as a `recursive` parser. In some places I need to get `body` values where `body` is a parser that relies on `statement`. For now, it looks like this:

```rust
fn statement() -> impl Parser<char, Statement, Error = Simple<char>> {
    recursive(|statement| {
        let body = statement.repeated().map(|stmt| Body { stmt });

        // I can use 'body' below
    }
}
```

What I'd like to do is to extract `body` from here as I'd also like to use it in some other functions.

How can I do that with Chumsky?

Thanks in advance for your help!

**Comment by zesterer** [comment]
Hello,

You can solve this problem using the [`Recursive::declare`](https://docs.rs/chumsky/latest/chumsky/recursive/struct.Recursive.html#method.declare) and [`Recursive::define`](https://docs.rs/chumsky/latest/chumsky/recursive/struct.Recursive.html#method.define) functions, allowing you to entirely separate the definition of a parser from its declaration. This way, you can declare all of your interdependent parsers first, and then define them later on. In fact, `recursive` is just a thin wrapper around these functions!

**Comment by ClementNerma** [comment]
Thanks, I'll look into that :)
