### ISSUE TITLE
Idiomatic way to enforce different parsers for different sections?

### ISSUE THREAD

**Issue by muja** [zesterer/chumsky#218]
My inputs are a templating language. Outside of an expression section delimited by `@(` and `)`, every input is valid. But inside, only valid syntax is allowed. Using `or(any())` will unfortunately consume all inputs on first non match. Using `filter(|c| *c != '@')` instead of `any` also skips single '@'s which are valid. I was able to consume single '@'s in a different `or`, however if there is illegal syntax inside the @(), it will always fallback to this... And all in all it seems hacky.

valid:

`Hello @(valid_expr)`
`Hello @("World")`
`Hello from me@example.org`

invalid:

`Hello @("World)`

Do you have any suggestions? My current code (roughly):

```rust
// other parsers
.or(filter(|c| *c != '@')
    .repeated()
    .at_least(1)
    .collect::<String>()
    .map_with_span(Template::Text))
.or(expression
    .padded()
    .delimited_by(just("@("), just(")"))
    .map_with_span(Template::Expression))
.or(filter(|c| *c == '@').map_with_span(Template::Char))
```

As you can see here my last example will yield `[Template::Text("Hello "), Template::Char('@'), Template::Text("(\"World)"]` which I don't have a good solution for.

also do you think it would make sense to use a Lexer for a templating language since ~99% of inputs is kept as-is.

**Comment by zesterer** [comment]
It sounds like you want to use a recovery strategy. Something like

```rs
...
just('@').ignore_then(expression
    .padded()
    .delimited_by(just("("), just(")"))
    .map_with_span(Template::Expression))
    .recover_with(nested_delimiters('(', ')', [], |_| Template::Error)))
...
```

This would allow it to treat a malformed expressions as a valid AST node, while still generating errors for it.

**Comment by muja** [comment]
Unfortunately I couldn't get your example to working, because while the fallback lambda `|_| Template::Error` gets called, it still treats it as an error and falls back to other `or` parsers. No idea why, but I can't seem to get a `Template::Error` in my parser result.

However, I found that `take_until(just("@(")).map(|chars, _| chars).collect().map(Template::Text)`, while a bit unergonomic due to having to additionally use `map` does exactly what I need.

BTW. Thank you for this awesome library that really got me addicted!
