### ISSUE TITLE
Recursive parser with `or` always uses the `or` parser even though input is valid for initial parser

### ISSUE THREAD

**Issue by muja** [zesterer/chumsky#219]
I don't know how to elaborate further, whether this is a bug or I'm misunderstanding/misusing. Minimal working example:

```rust
use chumsky::prelude::*;

#[derive(Debug, Clone, Eq, PartialEq)]
enum Token {
    Ident(String),
    Number(String),
    Ctrl(String),
}

fn main() {
        println!(
            "begin end={:?}",
            recursive(|value| {
                just::<char, _, Simple<char>>("BEGIN")
                    .to(Token::Ctrl("BEGIN".to_owned()))
                    .chain(value.clone().padded().repeated().flatten())
                    .chain(just("END").to(Token::Ctrl("END".to_owned())))
                    .or(text::int(10)
                        .map(Token::Number)
                        .or(text::ident().map(Token::Ident))
                        .map(|e| vec![e]))
            })
            .parse(r#"BEGIN 42 END"#)
        ); //=> Ok([Token::Ident("BEGIN")])
}
```

This returns `Ok([Token::Ident("BEGIN")])` instead of the expected `Ok([Ctrl("BEGIN"), Number("42"), Ctrl("END")])`

Using non-recursive parsing works:
```rust
use chumsky::prelude::*;

#[derive(Debug, Clone, Eq, PartialEq)]
enum Token {
    Ident(String),
    Number(String),
    Ctrl(String),
}

fn main() -> {
        println!(
            "begin end={:?}",
                just::<char, _, Simple<char>>("BEGIN")
                    .to(Token::Ctrl("BEGIN".to_owned()))
                    .chain(text::int(10)
                    .map(Token::Number).padded().repeated())
                    .chain(just("END").to(Token::Ctrl("END".to_owned())))
                    .or(text::int(10)
                        .map(Token::Number)
                        .or(text::ident().map(Token::Ident))
                        .map(|e| vec![e]))
            .parse(r#"BEGIN 42 END"#)
        ); //=> Ok([Ctrl("BEGIN"), Number("42"), Ctrl("END")])
}
```

How would I achieve the same result using recursive parsing?

Is there something like a negative parser? That would be very useful for cases like these and some others… something like `not(just("BEGIN")).ignore_then(text::ident())` would be extremely useful but I couldn’t find it anywhere.

**Comment by zesterer** [comment]
I think most of your questions here would be answered by following [the tutorial](https://github.com/zesterer/chumsky/blob/master/tutorial.md). That said, there are two comments I have that should help:

1) Parsers are lazy. They parse as much as they can recognise, and no more. If you want them to try to parse the entire input (and fail if they can't) you should use `.then_ignore(end())` at the end, forcing them to try parsing to the end.

2) Your use of `recursive` looks like it would be much better served by `.repeated()`, allowing you to parse zero or more instances of a pattern.

**Comment by muja** [comment]
Hey. I actually tried the tutorial before starting to use chumsky. Unfortunately using repeated() and end() respectively doesn't work in my case, because I'm trying to parse a 3rd party syntax and there, I only want to recurse in specific cases.

I realize that parsers are lazy, and that if I had used the `then_ignore(end())`, I would force the parser to select the Ctrl path. But it's only possible here and not in my real program.

To elaborate a bit further, unfortunately the (3rd party syntax) I'm dealing uses the keyword "END" ambiguously, or, rather, it has special meaning at the end of a program, where any following input is not parsed at all. But the same keyword can appear in the middle, nested however often (delimited by a "BEGIN") where it acts as a simple delimiting keyword and parsing continues as usual. For example, the following syntax is legal:

```
TEXT zipcode := "111"
END
somerandomgibberish20342893"asdf2j//  
```

but this is not:
```
DATASTRUCTURE Address BEGIN
    TEXT zipcode
END
somerandomgibberish20342893"asdf2j//  
```

...

**Comment by zesterer** [comment]
Right, that makes sense.

In your original example, what's the reason for using `chain`? Your code currently requires an integer to appear immediately after `BEGIN`, without even whitespace. Did you mean to use `or` instead?

As an aside, You could use `text::keyword("BEGIN")` too, it avoids `BEGINNING` being parsed as `BEGIN` followed by `NING`.

**Comment by muja** [comment]
Yes that is a common issue in my parser, and .then_ignore(text::whitespace()) seems to also not work since it accepts 0 whitespace characters. I seem to have missed text::keyword, for that I thank you so much! And looking at it's implementation, I also discovered `try_map`, which was the missing key and does everything I need! :)

I will try using text::keyword instead of just where possible from now on. By the way, my working example now (thanks again!):

```rust
println!(
    "begin end={:?}",
    recursive(|value| {
        text::keyword::<char, _, Simple<char>>("BEGIN")
            .to(Token::Ctrl("BEGIN".to_owned()))
            .chain(value.clone().padded().repeated().flatten())
            .chain(text::keyword("END").to(Token::Ctrl("END".to_owned())))
            .or(text::int(10)
                .map(Token::Number)
                .or(text::ident().try_map(move |c: String, span| {
                    if c.as_str() == "BEGIN" || c.as_str() == "END" {
                        Err(Simple::custom(span, "force fallback"))
                    } else {
                        Ok(Token::Ident(c))
                    }
                }))
                .map(|e| vec![e]))
    })
    .parse(r#"BEGIN 42 END"#)
); //=> Ok([Ctrl("BEGIN"), Number("42"), Ctrl("END")]) 🎉🥳
```

Also I'm using chain() here because the keyword BEGIN can be followed by repeated tokens and should be put into the same Vec. `or` would not be desired here, since they can appear together.
