### ISSUE TITLE
Help understanding when to map the span tokens exactly.

### ISSUE THREAD

**Issue by mainrs** [zesterer/chumsky#22]
Hey!

I am still a little bit confused on when _exactly_ I should to use `map_with_span`. I've taken a look at the examples in this repo and they basically do it all at the end on the last parser that gets returned. But after taking a look at the code in `tao`, you often do it in between as well.

Besides, could you enable GitHub Discussions on your repositories as well? That way the issue tracker doesn't get cluttered with questions like these :) 

Have a great week!

**Comment by zesterer** [comment]
> I am still a little bit confused on when exactly I should to use map_with_span. 

`map_with_span` doesn't do anything on its own: it simply allows you to grab the span of the input that a parser consumed. You can use it wherever is most convenient for you.

For example, consider a parser like...

```
text::int(10)
    .map_with_span(|n, span| (n, span))
    .padded()
    .repeated();
```

...that gets used to parse...

```
42 87 3 19
```

The output would be:

```
[
    ("42", 0..2),
    ("87", 3..5),
    ("3", 6..7),
    ("19", 8..11),
]
```

As you can see, the provided span is only that of the input that was consumed by the parser.

> But after taking a look at the code in tao, you often do it in between as well.

I would caution against Tao being used as a canonical reference right now. I'm still very early on in the compiler's rewrite.

> Besides, could you enable GitHub Discussions on your repositories as well?

Sure, I've just done that!

**Comment by mainrs** [comment]
Thanks for the help!
