### ISSUE TITLE
Force consuming input?

### ISSUE THREAD

**Issue by rongcuid** [zesterer/chumsky#228]
Assume I want to parse the following two integer formats:

```
\d+ // Base-10 integer
0x[[:xdigits:]]+ // Base-16 integer
```

Right now, this is what I do:

```rust
  let int10 = text::digits(10)
      .map(|s: String| i64::from_str_radix(&s, 10).expect("int10"));
  let int16 = just("0x").ignore_then(
      text::int(16).map(|s: String| i64::from_str_radix(&s, 16).expect("int16")),
  );
int16.or(int10)
```

Unfortunately, the error recovery doesn't work as well as I'd like. Say I have an input `0xG`, which is invalid. The parser tries `int16`, failing, then tries `int10`, giving `0`, leaving the parser pointing at the `x`. I would really like the `0x` to be consumed when `int16` parses.

**Comment by zesterer** [comment]
You could have a fallback pattern for this case, like the following:

```rs
let interr = just("0x").then(filter(|c| c.is_alphanumeric()).ignore().repeated())
    // Always generate an error for this case
    .try_map(|o| Err(/* Error: not a valid integer literal*/));

int16.or(int10).or(interr)
```

**Comment by rongcuid** [comment]
How does `interr` work? I think `int10` would match `0` and succeed here.

**Comment by zesterer** [comment]
Alternatively, a 'neater' solution might be a combination of both:

```rs
let int10 = filter(|c| c.is_alphanumeric()).repeated().collect::<String>()
    .try_map(|s: String| i64::from_str_radix(&s, 10)
        .map_err(|e| /* Error: invalid base 10 literal */));
let int16 = just("0x").ignore_then(
    filter(|c| c.is_alphanumeric()).repeated().collect::<String>()
        .map(|s: String| i64::from_str_radix(&s, 16)
            .map_err(|e| /* Error: invalid base 16 literal */)),
);
int16.or(int10)
```

**Comment by zesterer** [comment]
Closing because I believe the resolution here is fairly clear: make the parser more permissive than the grammar allows, and then use a combinator like `try_parse` or `validate` to narrow the grammar further.
