### ISSUE TITLE
Having trouble capturing empty lines as a token

### ISSUE THREAD

**Issue by rvcas** [zesterer/chumsky#230]
I'm using chumsky for https://github.com/aiken-lang/aiken

In the lexer, which I used tao as a starting point for, I'm having some trouble properly capturing `Token::EmptyLine`.

https://github.com/aiken-lang/aiken/blob/main/crates/lang/src/parser/lexer.rs#L34

I suspect it's because newlines in this situation are being consumed by the use of `padded` in the final choice at the end of the lexer.

I wasn't sure where to get some help, so apologies if an issue is not appropriate.

Have you seen this kind of situation before? and if so do you happen to have a recommendation for how to capture this token correctly?

**Comment by zesterer** [comment]
Yes, `.padded()` will consume all whitespace including newlines. If you want to avoid this, you can do something like `.padded_by(one_of(" \t").ignored().repeated())` to consume all space and tab characters before and after the pattern.

**Comment by rvcas** [comment]
@zesterer that worked perfectly thanks
