### ISSUE TITLE
Syntax suggestion for select!

### ISSUE THREAD

**Issue by muja** [zesterer/chumsky#234]
I've seen you updated select to optionally accept a span in `master`. However with the way it is implemented right now, `span` must be defined on every enum path. I've used the following implementation quite successfully:

```rust
macro_rules! select {
    (|$span:ident| $($p:pat $(if $guard:expr)? => $out:expr),+ $(,)?) => ({
        chumsky::primitive::filter_map(move |$span, x| match x {
            $($p $(if $guard)? => ::core::result::Result::Ok($out)),+,
            _ => ::core::result::Result::Err(chumsky::error::Error::expected_input_found($span, ::core::option::Option::None, ::core::option::Option::Some(x))),
        })
    });

    ($($p:pat $(if $guard:expr)? => $out:expr),+ $(,)?) => (select!(|_span| $($p $(if $guard)? => $out),+));
}
```

This way `span` can only be specified once: `select!(|span| Token::Literal(s) => (span, Value::Literal(s)))`

I think this also easier to read, but that's probably a matter of opinion. If you want I can create a PR

**Comment by zesterer** [comment]
I think this would be acceptable. IIRC the span feature isn't yet in a release, so this wouldn't be a breaking change. If you want to open a PR, feel free!
