### ISSUE TITLE
Conditionally parsing patterns based on the output of a parser (question)

### ISSUE THREAD

**Issue by Nughm3** [zesterer/chumsky#235]
So I'm using `chumsky` to write a parser for an "everything is an expression"-style language. For example:

```rust
enum Stmt {
     ExprStmt(Expr),
     // ...
}

enum Expr { /* binary, unary, if, else... */ }

fn stmt() -> impl Parser<Token, Stmt, Error = Simple<Token>> { /* ... */ }
fn expr() -> impl Parser<Token, Expr, Error = Simple<Token>> { /* ... */ }
```

After parsing an expression, I may want to consume a semicolon, depending on what the expression was. Rust does this:

```rust
let x: bool;

x = true;
if x {
    println!("x was true");
}
```

The semicolon is mandatory after the assignment expression, but optional after the if expression. So `expr()` needs to know what it just parsed, and conditionally `.then_ignore(';')` if that kind of expression wasn't a control expression.

In a normal parser which keeps its own state, I would just have `match`ed on the output of `expr()`, then called `consume(';')` if needed. However, you can't really directly manipulate the parser state here.

How can I implement this with `chumsky`? Do I need to use `custom()` somehow?

**Comment by zesterer** [comment]
You can actually solve this by splitting the parser into 'block-like' expressions and 'inline' expressions, and then requiring a semicolon after the latter but not after the former to make a statement. If you take a look at the `nano_rust` example, you'll see this approach in action.

**Comment by Zij-IT** [comment]
Or if you want to make your head spin you can look at the unofficial specification of Rust, which follows the answer recommended by zesterer (:

https://doc.rust-lang.org/reference/statements.html#expression-statements

**Comment by Nughm3** [comment]
Thanks for the suggestions! I'll try it out.
