### ISSUE TITLE
How to do error recovery that *adds* tokens

### ISSUE THREAD

**Issue by MalekiRe** [zesterer/chumsky#236]
Hey, I'm working on my own language using this parser, and all the error recovery options appear to be for skipping/removing/consuming tokens. I'm not sure if what I am thinking is the proper way to go about it, but if I have a language construct like a function arguments `my_function(1, 2, 3)` and I miss a comma `my_function(1, 2 3)` I think that the proper move here would be an error recovery strategy that would *add* a `,` comma token and see if that fixed the input. I don't know though, thoughts?

**Comment by zesterer** [comment]
I think the best approach here would probably be to attempt to parse the correct pattern, and then fall back to a lot lenient parser that tries to deal with such errors, generating an error in the process. This should be possible with the new recovery strategy introduced in #107.

**Comment by zesterer** [comment]
Closing because the approach chumsky takes when performing error recovery is to generalise parsers over erroneous inputs and emit ancillary errors in the process instead of trying to 'fix' the original input.
