### ISSUE TITLE
zero_copy::combinator::AndIs behavior

### ISSUE THREAD

**Issue by herkhinah** [zesterer/chumsky#241]
From the wording `AndIs` I would expect the second parser to only get the section the first parser parsed as input. This would allow the second parser to make use of `end()` to check if it parses the same amount of input as the first parser.

The behavior of the current implementation seems to be, that the second parser can parse more input than the first parser, while at the same time after the second parser finishes the input is rewinded to the position of the first parser.

**Comment by zesterer** [comment]
The behaviour you suggest might initially appear more consistent, but also makes the combinator less powerful, and in ways we do actually care to cater for. Consider the following:

```rs
let escape = just("\\n").or(just("\\t")).or(just("\\\""));

let unescaped_char = any().and_is(escape.or(just('"')).not());

// `unescaped_char` parses `\` followed by more of the string, but not `\n`, `\t`, or `\"`
```

Here, the 'second parser can read further than the first parser' behaviour is actually a benefit and provides the ability for the parser to look ahead to detect string escape sequences.

**Comment by herkhinah** [comment]
How about `and_is` accepting a lambda where the lambda argument is the number of tokens parsed by the previous parser? Then use cases where it would be relevant to know how many tokens the previous parser has parsed would also be covered. (I've encountered one use case but I've solved it another way and now I can't remember what it was)
```
let parser1 = ...;
let parser2 = ...;
parser1.and_is(|num_of_tokens| parser2.repeated().exactly(num_of_tokens));
```

**Comment by zesterer** [comment]
This only works in the very specific case where `parser2` parses exactly one token, no more and no less. I'm just not sure I really see a use-case for this that can't already be solved through other means.

**Comment by zesterer** [comment]
Closing because I don't think this change in behaviour is desirable for most cases. It might be worth considering to what extent this use-case crops up in the future though.
