### ISSUE TITLE
Question about span

### ISSUE THREAD

**Issue by herkhinah** [zesterer/chumsky#246]
What's the use of `Span` in `Input` and how does it differ from `Offset`? Do they have a different semantic meaning, like `Offset` being the n-th token and then `Input::span(range)` answers what span of the source code gets covered by that token range?
I assumed this because I'm not sure what other purpose `Input::span` could have that's not covered by `Offset` but with that interpretation my `Input` implementation for a struct that wraps a `Vec` of token/span tuples crashes.

**Comment by zesterer** [comment]
Spans are user-facing. The user can access them with `map_with_span` in order to annotate their AST with spans. Offsets are internal, and are used for tracking progress through the input for the sake of error prioritisation.

**Comment by herkhinah** [comment]
mew, then it has exactly the use case I had in mind. I was confused what Span was about because `Input::span` gets called with an out of bounds `Offset` range.
