### ISSUE TITLE
Idea: zero_copy `parse` returns a custom struct

### ISSUE THREAD

**Issue by CraftSpider** [zesterer/chumsky#249]
Mostly inspired by the fact that it effectively seems to want `WarnResult` - `Ok(T)`, `Warn(T, Vec<E>)`, and `Err(Vec<E>)`

**Comment by zesterer** [comment]
Ah, perhaps with methods on that struct to fetch the AST/errors?

**Comment by CraftSpider** [comment]
Yeah - you could decompose it into `Option<Ast>` or `Vec<Error>`, but I feel like it would make it
- More clear than the current `.0` or `.1`
- Easier to distinguish the warnings case

This may just be my like of dedicated types over tuples in most situations, but I think it makes sense here.

**Comment by zesterer** [comment]
I like this idea, it solves the current plethora of `parse`-like functions quite cleanly.

```rs
foo.parse("...") // ParseResult<O, Self::Error>

foo.parse("...").output() // Option<&O>
foo.parse("...").into_output() // Option<O>

foo.parse("...").errors() // &[Self::Error]
foo.parse("...").into_errors() // Vec<O>

foo.into_result() // Result<O, Vec<Self::Error>>

// Should we choose to add warnings (I think they'd be a good idea!)
foo.parse("...").warnings() // &[Self::Warning]
foo.parse("...").into_warnings() // Vec<Self::Warning>
// 
```

**Comment by CraftSpider** [comment]
Gonna close this, as the original intent has been implemented, and I think future additions can be tracked on their own
