### ISSUE TITLE
Using `.repeated()` ignores parse errors

### ISSUE THREAD

**Issue by audunhalland** [zesterer/chumsky#268]
Hi! I'm trying out Chumsky in my project, and discovered something a bit strange:

```rust
fn simplistic_parser<'s>() -> impl Parser<char, &'s str, Error = Simple<char>> {
    just("foobar")
}

simplistic_parser()
    .repeated() // <--- here
    .parse("something invalid")
    .expect_err("should fail");
```

Using `repeated()` on some parser stops internal parse errors from propagating out. My interpretation is that Chumsky believes that an error recovery has happened here. But I haven't told Chumsky to do any error recovery, and expect that invalid syntax will be properly reported.

Without `repeated()` this parse fails as expected.

**Comment by bew** [comment]
`repeated` by default can accept zero or more matches.
To enforce the need to have at least one match you can use `.repeated().at_least(1)`

**Comment by audunhalland** [comment]
Let's say I'm parsing a source file containing a sequence of statements. I'd still want to accept zero statements as valid input. But I don't want to accept any statements that are _invalid_.

**Comment by CraftSpider** [comment]
JFor parsing a source file, you likely want something like `.then_ignore(end())` as the final statement in your parser. Parsers are lazy by default, and accept as little input as necessary, but `end()` only succeeds if the parser has consumed all of its input.

**Comment by audunhalland** [comment]
`.then_ignore(end())` solves the problem, thank you :)

I guess I had misunderstood parser laziness.

**Comment by zesterer** [comment]
@CraftSpider @bew I feel like this case is hit commonly enough that perhaps the default `Parser::parse` method should implicitly add a `.then_ignore(end())`, with a separate method to opt out of this behaviour (it's rare for lazy parsing on the top level parser to be the desired outcome anyway).

This shouldn't break existing parsers that use `.then_ignore(end())` because `EoI` gets produced 'forever' once a stream is exhausted.

Do you have any thoughts about this being changed for `zero-copy`?

**Comment by bew** [comment]
> I feel like this case is hit commonly enough that perhaps the default `Parser::parse` method should implicitly add a `.then_ignore(end())`, with a separate method to opt out of this behaviour (it's rare for lazy parsing on the top level parser to be the desired outcome anyway).

I agree with you. What about streaming inputs? (never worked with those) is there even a end?

**Comment by zesterer** [comment]
> I agree with you. What about streaming inputs? (never worked with those) is there even a end?

What do you mean by streaming inputs? something like bytes from an `io::Read`? In that case, the behaviour is the same as with `Iterator::for_each`: we keep going until we reach a `None`, and then we assume the end has been reached.
