### ISSUE TITLE
Look ahead? PEG's 'and' and 'not' operators.

### ISSUE THREAD

**Issue by lfnoise** [zesterer/chumsky#278]
Are there combinators for PEG's 'and' and 'not' operators? Chumsky's 'not' operator is not the same as it consumes input, unlike PEG 'not'. 
Are there any Chumsky combinators that parse and then do not consume on success (= look ahead)?

[From Wikipedia:](https://en.wikipedia.org/wiki/Parsing_expression_grammar)
The and-predicate expression &e invokes the sub-expression e, and then succeeds if e succeeds and fails if e fails, but in either case never consumes any input.
The not-predicate expression !e succeeds if e fails and fails if e succeeds, again consuming no input in either case.

Thank you.

**Comment by zesterer** [comment]
In the to-be-merged `zero-copy` branch, `not` behaves as you describe, without consuming input. There will also be an `and_is` combinator that behaves as you describe for `and`.

For now, you can emulate these behaviour with the `rewind` combinator (which, on success, rewinds the input stream to wherever it was before attempting the parse) like so:

PEG-style `not`: `a.not().rewind()`

PEG-style `and`: `b.rewind().ignore_then(a)`

**Comment by zesterer** [comment]
Closing, because this is going to be happening soon anyway.
