### ISSUE TITLE
I want to pass to parser a context which persists longer than parser and spans

### ISSUE THREAD

**Issue by rnarkk** [zesterer/chumsky#292]
chumsky’s design suggestion is that you wrap your AST nodes by additional `Spanned` layer which inevitably makes it part of your AST design. This might be fine if you only think about parser, but once you also want printer expecting the same AST input to output string, this additional spanned layer becomes simple overhead/chore wanting you to fill dummy span around every time you construct AST nodes programatically (see rustc‘s or swc’s use of `DUMMY_SP`).

So I want instead to store Spans to my context persisting longer than Parser and Spans themselves. This design choice would make parser-printer relationship more symmetrical.  Existing `map_with_span` method takes closure but closure cannot take mutable reference (of context). So I want parser to have my context throughout parsing phase (so I can get it from inside parser).

**Comment by zesterer** [comment]
The up-coming `zero-copy` rewrite actually features this: parsers can be parameterised with a 'state' type parameter, and can then fetch that state mutably while parsing with `map_with_state`. `zero-copy` should be usable within about a month, I'll make sure to update you when it's ready.

**Comment by rnarkk** [comment]
Just beautiful! Thank you. Leaving you to keep this issue open or close it.

**Comment by rnarkk** [comment]
I'm so curious about the up-coming `zero-copy` rewrite, whether it would also ensure pointer-wise identity between `O`s as in `MapWithState<Self, F, O>` and `try_map(self, f: F) where : Fn(O, ..) -> ..` being applied to the former. Because I want to store/retrieve Spans to/from my context based on the keys outputted from `fmt::Pointer`.

**Comment by zesterer** [comment]
I'm not sure what you mean by 'pointer-wise identity'. Rust doesn't generally promise anything about whether values are or are not moved, and this is particularly true when passing things by value through functions.

**Comment by zesterer** [comment]
Closing because the original requested feature is coming soon (see #261).

**Comment by zesterer** [comment]
If you're happy to rely on one of the alpha releases, this is currently available through crates.io. A final release is getting closer, but there are still some minor things to address yet.
