### ISSUE TITLE
parsing '{{ }}'

### ISSUE THREAD

**Issue by jakobhellermann** [zesterer/chumsky#3]
I'd like to parse '{{ some text }}' as " some text ".

The version using just '{' and '}' as delimiters works fine like this:
```rust
let inner = none_of("}".chars()).repeated().collect::<String>();
let parser = just('{').padding_for(inner).padded_by(just('}'));
```

but I'm stuck defining `inner` for the '{{' '}}' case.
The `Stream` can only peek one token, so I see no way to take all characters until '}}' is encountered.

Is there anything I'm missing?

**Comment by jakobhellermann** [comment]
I guess I'm looking for something like noms `take_until`: https://docs.rs/nom/7.0.0/nom/bytes/complete/fn.take_until.html

**Comment by zesterer** [comment]
This isn't a pattern that's LL(1) parseable. A pattern like this would generally be handled by a lexer, and it's quite common for lexers to be hand-written so that they can deal with the precise idiosyncrasies of tokenisation.

**Comment by jakobhellermann** [comment]
I see, thank you.

**Comment by zesterer** [comment]
As a point of interest, chumsky has now been rewritten from the ground up to support parsing LL(k) grammars, so this pattern is now parseable.
