### ISSUE TITLE
Add `proc_macro` impls

### ISSUE THREAD

**Issue by CraftSpider** [zesterer/chumsky#312]
Add relevant trait implementations for `proc_macro`/`proc_macro2` behind a feature gate.

This is superior to an external crate because an external crate can't provide these implementations on the native types, and would need to add another layer of wrapping.

Thoughts?

**Comment by zesterer** [comment]
I'm not sure I understand. Is this to use chumsky to parse rustc token streams, or...?

**Comment by CraftSpider** [comment]
Yes, this would be allowing chumsky to be used in the creation of a proc macro to parse input

**Comment by CraftSpider** [comment]
Update: With the recent additions of `Stream` and `nested_in`, this actually already works. Just call `Stream::from_iter(ts.into_iter)` and use `nested_in` to split up `TokenTree::Group`
