### ISSUE TITLE
Volatile error recovery output?

### ISSUE THREAD

**Issue by max-sixty** [zesterer/chumsky#317]
Over at https://github.com/PRQL/prql/pull/2002, I'm seeing that our tests are producing different output on each run.

So running `cargo insta test --accept` on that branch gives:

```diff
diff --git a/prql-compiler/src/test.rs b/prql-compiler/src/test.rs
index 6958f7e..9036579 100644
--- a/prql-compiler/src/test.rs
+++ b/prql-compiler/src/test.rs
@@ -2966,7 +2966,7 @@ fn test_errors() {
        │
      1 │ Mississippi has four S’s and four I’s.
        ·                                       ┬
-       ·                                       ╰── identifier expected * or an identifier, but found
+       ·                                       ╰── identifier expected an identifier or *, but found
     ───╯
     "###);
 
```

...and running it again will give a slightly different result.

Is this expected?

(I'm not asking anyone to debug PRQL's tests... Just from the Chumsky perspective, is this expected / is there some way of handling?)

**Comment by CraftSpider** [comment]
If you're using the built-in `Simple` error type, this is expected - it stores expected tokens as a `HashSet`, which has non-deterministic ordering. That, in turn, means error display may place tokens in a random order each run.

**Comment by max-sixty** [comment]
Thanks for the swift reply. 

> If you're using the built-in `Simple` error type, this is expected - it stores expected tokens as a `HashSet`, which has non-deterministic ordering. That, in turn, means error display may place tokens in a random order each run.

Is there a reasonably close way of having it be deterministic? We'd be happy to do something hacky. Or would it require a fairly deep change in Chumsky?

The non-determinism is difficult to test around — it would be tractable if it were just a few instances, but this would mean all our error messages will be volatile.

**Comment by zesterer** [comment]
For a project as large as PRQL, I'd recommend having a custom error type anyway: it gives you more precise control what errors are reported, what information they contain, and how they're combined.

The non-determinism is indeed a little annoying, I'll look into using a static RNG for the `HashSet`.

**Comment by max-sixty** [comment]
Great; it sounds like we create the message ourselves and so can sort the items before displaying.

Thanks for the help! I'll close
