### ISSUE TITLE
Implement `labelled` extension API

### ISSUE THREAD

**Issue by zesterer** [zesterer/chumsky#330]
Pre-rewrite released had the [`.labelled(...)`](https://docs.rs/chumsky/0.9.2/chumsky/trait.Parser.html#method.labelled) API, to allow annotation patterns with labels that would show up in error messages.

Something similar should be implemented in the rewrite, ideally through extension trait(s) upon `Error`.

**Comment by Zij-IT** [comment]
Besides adding an example for `Parser::labelled`, is there anything that needs to be done for this to be closed?

**Comment by zesterer** [comment]
I don't think so, I'd say this has been done now.
