### ISSUE TITLE
NanoRust example does not work

### ISSUE THREAD

**Issue by jeffparsons** [zesterer/chumsky#34]
On master (9a2787adcf2937152f0d562a22e51512cdfc1d4d):

```
Hello, world!
The meaning of life is...
...something we cannot know
However, I can tell you that the factorial of 10 is...
Error: 'factorial' called with wrong number of arguments (expected 1, found 2)
    ╭─[<unknown>:22:18]
    │
 22 │        print(factorial(10, 11));
    ·                       ────┬───  
    ·                           ╰───── 'factorial' called with wrong number of arguments (expected 1, found 2)
────╯
```

It would be good for these to be checked in CI.

In this case the only issue preventing it from succeeding is precisely what the diagnostic is telling us, which is super cool. :grinning: Though I'd suggest this is a good candidate for rustc-style "UI tests", maybe using something like "trybuild" if https://github.com/dtolnay/trybuild/issues/64 were implemented (which might be a worthwhile "yak") because checking that it prints the expected output on success is probably important, too.

**Comment by zesterer** [comment]
This is actually deliberate and is intended to demonstrate that source spans are propagated all the way through to runtime.

I understand that this is probably unintuitive though so I'll fix the example and instead add a comment encouraging users to play around with the sample to see what errors they can produce!

**Comment by zesterer** [comment]
I've fixed this in e627ae0 (and included support for comments!).

**Comment by jeffparsons** [comment]
> This is actually deliberate and is intended to demonstrate that source spans are propagated all the way through to runtime.

Haha, it did cross my mind that this might be deliberate, but then I thought "surely there would be a comment if so". 😅

I think hooking up trybuild could still be valuable. I'm happy to give it a go if you're interested.

Thanks!

**Comment by zesterer** [comment]
If that's something you're interested in doing, I'd definitely accept the PR!
