### ISSUE TITLE
The `Seq` parser should yield the input it consumes

### ISSUE THREAD

**Issue by p-e-w** [zesterer/chumsky#37]
It's strange that `Seq` yields the unit type, while `Just` yields its input. This makes `Seq` useless if you combine multiple `Seq` parsers with `or` and then want to know which one matched.

In general, I find matching strings in a `char` parser to be too cumbersome. I have code that looks like this

```rust
just('=').chain(just('='))
  .or(just('!').chain(just('=')))
  .or(just('<').chain(just('=')))
  .or(just('<').to(vec!['<']))
  .or(just('>').chain(just('=')))
  .or(just('>').to(vec!['>']))
```

when all I really want is something like

```rust
one_of(&["==", "!=", "<=", "<", ">=", ">"])
```

This doesn't currently seem to be provided by Chumsky's built-in functions. I realize that this pattern may not generalize to arbitrary token types, but character-based parsers are extremely common, so it might make sense to have some special functions for this purpose.

**Comment by zesterer** [comment]
My original reasoning for this was to avoid allocating a `Vec` of tokens and immediately dropping it (Rust's optimiser can't currently reason about allocations), but I realise that this is an important use-case so I'm tempted to change this behaviour in a later version (a lot of Chumsky's allocators internally perform small allocations: it feels like an issue that requires a more general solution, like parameterising combinators with collection types).

**Comment by zesterer** [comment]
The `seq` function has now been deprecated, `just` now covers all of these cases (it accepts tokens, arrays of tokens, vectors of tokens, slices of tokens, string, etc.). I'm closing this issue for now, but I'm happy to open it again if this is still a problem.
