### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by mainrs** [zesterer/chumsky#38]
Hey!

I've taken a look at the code and their doesn't seem to be any reason besides `error.rs` to make the crate `no_std` compatible (only taking the code into consideration). The problems with the above mentioned file are:
1) The error implements `std::error::Error`. This can be put behind a feature flag.
2) It uses `HashSet`, which is not available on `no_std`. The next best solution would be `BHashSet`, but that requires it's data to be `Ord`. And this doesn't always make sense.

Is this something you have considered/thought about? 

I am asking because I have a parser and wanted to have a version that runs on the web as well. `no_std` would be the best solution! :)

**Comment by zesterer** [comment]
I think it should definitely be possible and I'd like to see it happen! As you mention, the changes are likely to be relatively simple. I might have time to look into this after Christmas or, alternatively, I'd happily accept a PR!

**Comment by mainrs** [comment]
I can open a PR, sure. I did some research and found [hashbrown](https://github.com/rust-lang/hashbrown). It's the same library used in `std`. The difference is that by using the library directly you get access to a `no_std`-compatible one. As noted in its readme though, the default hasher used to generate the hashes has not the same HashDoS resistance as the one used in `std`. I don't think that that is a problem in this use-case.

So I'd probably use `cfg` attributes to use the library if `no_std` is enabled. The rest should be fairly easy to port over.
