### ISSUE TITLE
fold with state

### ISSUE THREAD

**Issue by MechSlayer** [zesterer/chumsky#381]
Is there any way to access the parser's state in the foldl closure? kinda like map_with_state

**Comment by zesterer** [comment]
Not yet, although we have an issue about this: #308

Implementing `foldl_with_state`/`foldr_with_state` would be fairly trivial, although I am somewhat uncomfortable about the proliferation of `_with_state` versions of methods: but for now it seems like we have no option given Rust's lack of effect system.
