### ISSUE TITLE
`and_is_not` primitive

### ISSUE THREAD

**Issue by gimbles** [zesterer/chumsky#386]
Similar to `and_is`, `and_is_not(parser)` would basically be an alias for `and_is(parser.not())`

I can send a PR for this if I get a +1 =)

**Comment by zesterer** [comment]
I'm unconvinced that this provides sufficient utility above `a.and_is(b.not())` to be honest. I'd rather not inflate the crate with more combinators, especially those that are fairly trivial to compose out of others.

**Comment by gimbles** [comment]
Fair enough, I suggested this because I felt that the `not` being postfix in this case slightly brought unreadability, but I can see how it can be needless.

**Comment by zesterer** [comment]
> I suggested this because I felt that the `not` being postfix in this case slightly brought unreadability

I think I agree with this. In this case, importing it like so should work:

```rs
use chumsky::{prelude::*, Parser::not};

a.and_is(not(b))
```

**Comment by gimbles** [comment]
Aha! Seems good 👌🏻
