### ISSUE TITLE
Rename idea `and_is` -> `which_is`

### ISSUE THREAD

**Issue by bew** [zesterer/chumsky#388]
It always bothered me that `and_is` isn't very explicit that it'll apply something on the parser itself and not the rest.

I've recently thought about renaming it to `which_is`, which (not pun intended) I think is more explicit about the fact it's going to re-parse `self`

Also I think it reads a lot better, compare:
`any().and_is(not(just('\n')))` (using `not` directly as suggested at #386)
compared to:
`any().which_is(not(just('\n')))`

What do you think?

**Comment by zesterer** [comment]
I'm not opposed to this change, but I think we should remember that it's used in contexts other than just `any()`.

Additionally, `which` heavily implies that the *same* input parses as the second pattern, but this is not necessarily true: the second parser is permitted to parse more than the first.

**Comment by Zij-IT** [comment]
Closable?
