### ISSUE TITLE
Rule for when to clone parsers

### ISSUE THREAD

**Issue by edko99** [zesterer/chumsky#390]
I am trying to learn chumsky by following the tutorial and looking at the examples. I've noticed that sometimes sub-parsers are cloned, but other times not. I haven't been able to figure out the rule for when this is required, or any mention in the tutorial.

**Comment by zesterer** [comment]
The rule is simplify: clone when your parsers are `!Copy` and you need to use them again later. For example, `just("foo")` is `Copy`, but `foo.boxed()` is not.
