### ISSUE TITLE
Suggestion for a text parser: `decimal_number()`

### ISSUE THREAD

**Issue by LikeLakers2** [zesterer/chumsky#398]
Hi! I was looking at `chumsky` and found that there doesn't appear to be a built-in parser for recognizing decimal numbers, such as `4.21` or `4.2e-7`. So I'd like to suggest that one be added, since understanding number formats may be a common task for many chumsky parsers.

Looking through the examples, it appears the JSON parser example already implements a number parser:

https://github.com/zesterer/chumsky/blob/f664d7d7f36205bca58842233431927c14be69c0/examples/json.rs#L22-L37

so you could feasibly base the built-in parser off that code, instead of needing to figure it out from scratch. (Though I would recommend having the built-in parser return a string/vec rather than an f64, just in case the decimal number is more precise than an f64 can handle.)

**Comment by zesterer** [comment]
This is something I'd definitely like to integrate at some point, but it feels like this is better suited to an extension crate (or at least being behind a feature flag).

There are also a lot of subtle complications since number parsing varies a lot between languages. Even between C++ and Rust, two C-likes, there's the difference between `'` and `_` separators used to visually split up numbers.  This gets even more subtle when you get into scientific notation and the question of how to actually take the parsed number and precisely and correctly convert it into an actual float with the semantics that the language expects.

I'm happy to accept a PR for a simple form of this though, something that accepts an `int`, a full stop, and any number of trailing digits: I think that's a simple enough common denominator to cover a lot of small langs without introducing confusing functionality.

**Comment by LikeLakers2** [comment]
> This gets even more subtle when you get into scientific notation and the question of how to actually take the parsed number and precisely and correctly convert it into an actual float with the semantics that the language expects.

So wait, are you suggesting that this parser return a f32/f64 with the input it matched? Or do you think it should return a string/Vec<u8> with the input it matched?

**Comment by zesterer** [comment]
I'm not sure, to be honest! Outputting `f32`/`f64` means that we'd need to think carefully about how it deals with precision issues. Outputting the slice matched by it would just shift that responsibility on to the user.

**Comment by LikeLakers2** [comment]
Then might I suggest having more than one function, like `nom` does? To explain the parsers that `nom` has:

* Two parsers that parse the stream for a number, and return either [a `f32`](https://docs.rs/nom/7.1.3/nom/number/complete/fn.float.html) or [a `f64`](https://docs.rs/nom/7.1.3/nom/number/complete/fn.double.html).
* A parser that [returns the matched slice](https://docs.rs/nom/7.1.3/nom/number/complete/fn.recognize_float.html) (which you can use to perform your own parsing, such as piping the slice into `rust_decimal::Decimal::from_str`),
* A parser that [returns a tuple of the sign, integer, trailing digits, and exponent](https://docs.rs/nom/7.1.3/nom/number/complete/fn.recognize_float_parts.html) (not sure how useful this one would be).

I don't think we need to implement all of them, but offering a choice of the output format would prevent `chumsky` from needing to make decisions on behalf of the user, while simultaneously (and possibly significantly) reducing the workload on the user's end.

**Comment by LikeLakers2** [comment]
Sorry for bumping this, but I'm curious what you thought of the above suggestion? You seemed to suddenly stop replying, so I was unsure if you saw it and were thinking on it, or if you simply never saw it.

**Comment by LikeLakers2** [comment]
>Sorry, I've had a busy few weeks.

No worries. :) Just wanted to make sure that you saw it one way or another.

> I think a simple parser for decimals that accepts `int + '.' + digits` and outputs `f32`/`f64`

If I may ask, would this be one parser (which outputs one of those)? Or two parsers (one for each floating-point type)? 

If it's one parser, would we choose which type it outputs on behalf of the user, or would the user choose via turbofish syntax (presumably in combination with the `std::str::FromStr` trait)?

Or would this all be something we decide later?

> feel free to take a crack at implementing it if you feel up to it.

I may try my hand at it eventually - no guarantee though, since I need to get more experience with `chumsky` first.

**Comment by Zij-IT** [comment]
Out of curiosity, how would we feel about feature-gated `NumberParser` that uses [`lexical`](https://docs.rs/lexical/latest/lexical/) as the driver? It comes preloaded with a literal [ton of options](https://docs.rs/lexical/latest/lexical/format/index.html) that the user would be able to choose from (or even create their own).

The impl should be super simple and use [`lexical::parse_partial`](https://docs.rs/lexical/latest/lexical/fn.parse_partial.html), and then just move the input further along by the amount that was parsed by `parse_partial`.

**Comment by zesterer** [comment]
`lexical` seems like a good candidate! In particular, the `parse_partial` function looks like it's pretty much idea for integration into chumsky in a similar manner to the `regex` combinator. I think the best approach would be to copy the `regex` combinator and make modifications accordingly.

**Comment by Zij-IT** [comment]
@LikeLakers2

I believe the parser implemented in #462 and fixed in #465 will be of interest to you, as it changes the 17 line implementation of a JSON number parser into a one liner.

**Comment by zesterer** [comment]
> @zesterer You may want to give the benchmarks a look when using the `Number` parser for JSON. I may be benchmarking wrong, but I am getting a speedup of 46% and 42% for `json_chumsky_zero_copy_rich` and `json_chumsky_zero_copy_check_rich` respectively.

I'm also seeing similar. That said, this isn't particularly surprising to me: The existing JSON number parser does a lot of error generation internally and by using the new `number` parser, we pretty much skip all of that (at the cost of poorer errors). Effectively, we're reverting to the `EmptyErr` benchmark for the numeric parser *specifically*.

What is interesting to me is that swapping out the original chumsky-style numeric parser with `lexical` does pretty much nothing to the `EmptyErr` benchmark: this implies to me that what the compiler spits out after optimising the chumsky parser is of pretty much equivalent performance to that of `lexical` which is, in itself, quite remarkable. Really shows the power of zero-cost abstractions!

**Comment by Zij-IT** [comment]
This is closable, right? Recently I feel like a hunter for issues that are solved / completed :D
