### ISSUE TITLE
Trouble with mutual recursion

### ISSUE THREAD

**Issue by TGMM** [zesterer/chumsky#400]
This is kind of difficult to explain, so bear with me.
Let's say we have a parser that is trying to parse an `expression`, which we'll delimit with parentheses. This expression should contain a number inside it. Ex. `(10)`.
Now let's say we also have a parser that tries to parse a `list`, which we'll delimit with square brackets. This list should also contain a number inside. Ex. `[10]`.

The problem arises when the `expression` can contain either a number or a `list` and the `list` can contain either a number or an `expression`. The expression parser should be able to parse `([10])` and the list one should parse `[(10)]`.

As you can imagine, this parser is infinitely recursive, being able to parse something like `([([(10)])])`. 
Now, my question is, how can I write such a parser in chumsky? I come from `nom` where writing such a parser is [trivial](https://github.com/TGMM/chumsky_rec/blob/main/src/nom.rs), but my [chumsky attempt](https://github.com/TGMM/chumsky_rec/blob/main/src/chumsky.rs) doesn't compile at all. I know about the existence of the [recursive](https://docs.rs/chumsky/latest/chumsky/recursive/index.html) function, but I can't see how to make it work with mutual recursion.

**Comment by TGMM** [comment]
The `discussions` tab (which I wasn't aware of) has some [interesting solutions](https://github.com/zesterer/chumsky/discussions/263) to this problem. Closing this as it should've been a discussion. Apologies.

**Comment by zesterer** [comment]
For the sake of posterity, the usually approach to solving mutual recursion is to use [`Recursive::declare`](https://docs.rs/chumsky/1.0.0-alpha.3/chumsky/recursive/struct.Recursive.html#method.declare) to separate parser declaration from parser definition, allowing the construction of mutually-recursive parsers.

Note that this is also possible (if slightly less convenient) with [`recursive`](https://docs.rs/chumsky/1.0.0-alpha.3/chumsky/recursive/fn.recursive.html), like so:

```rs
recursive(|a| {
    let b = recursive(|b| {
        // Use `a` and `b` here in the definition of `b`
    });

    // Use `a` and `b` here in the definition of `a`
    a
})
```

*That said*, the example you gave does not actually require require true mutual recursion, only precedence climbing, which allows the use of only one `recursive`. Roughly speaking (this won't compile, but should give an idea of the rough structure):

```rs
recursive(|expr| {
    let literal = text::int();

    let list = expr.
        .separated_by(just(','))
        .delimited_by(just('['), just(']'));

    literal.or(list)
})
```
