### ISSUE TITLE
Example for map_with_state

### ISSUE THREAD

**Issue by edko99** [zesterer/chumsky#401]
Is there an example for `map_with_state`?
I am having a hard time making my closure compile when I try to mutate the state parameter. The documentation of the function shows code that corresponds to `map_with_span`.

**Comment by zesterer** [comment]
What sort of mutation are you performing? The lifetime of the state is local to the `map_with_state` closure, since it can't be permitted to outlive the function and invade the lifetimes of other parsers.

**Comment by edko99** [comment]
My interner is very simple: I put string slices (referencing the original text that I am parsing) in a hash map with a unique integer identifier for each. I return the integer identifier and that is what I use in my AST. The internal state is just a `RefCell<HashMap<&'a str, usize>>`.

Another case where internal mutability has saved me is with my Logos tokenizer's extras. It is the only way I found of having access to the extras after they are consumed by chumsky's token stream.
