### ISSUE TITLE
Parser::map_with_state example actually shows Parser::map_with_span

### ISSUE THREAD

**Issue by jamesyoungman** [zesterer/chumsky#402]
The doc comment for map_with_state looks like this (note that the example doesn't show map_with_state being used):

    /// Map the output of this parser to another value, making use of the parser's state when doing so.
    ///
    /// This is very useful for parsing non context-free grammars.
    ///
    /// The output type of this parser is `U`, the same as the function's output.
    ///
    /// # Examples
    ///
    /// ```
    /// # use chumsky::prelude::*;
    /// use std::ops::Range;
    ///
    /// // It's common for AST nodes to use a wrapper type that allows attaching span information to them
    /// #[derive(Debug, PartialEq)]
    /// pub struct Spanned<T>(T, SimpleSpan<usize>);
    ///
    /// let ident = text::ident::<_, _, extra::Err<Simple<char>>>()
    ///     .map_with_span(|ident, span| Spanned(ident, span))
    ///     .padded();
    ///
    /// assert_eq!(ident.parse("hello").into_result(), Ok(Spanned("hello", (0..5).into())));
    /// assert_eq!(ident.parse("       hello   ").into_result(), Ok(Spanned("hello", (7..12).into())));
    /// ```
    fn map_with_state<U, F: Fn(O, I::Span, &mut E::State) -> U>(
        self,
        f: F,
    ) -> MapWithState<Self, O, F>
    where
        Self: Sized,
    {
        MapWithState {
            parser: self,
            mapper: f,
            phantom: EmptyPhantom::new(),
        }
    }

**Comment by jamesyoungman** [comment]
The above code is from f664d7d7f36205bca58842233431927c14be69c0 which is current head, but the problem with the doc comment is older, I think the faulty checkin is 5fd3493dc1aee775f790a554d889deb52f50482a.

**Comment by zesterer** [comment]
Ah, yes. I think this is because the function was copied and then altered during development. I've yet to do the final 'doc check' pass before the 1.0 release, so there are a few items like this that leak through.

**Comment by CraftSpider** [comment]
I'm working on fixing some of these docs - are there any other functions I should take a look at?

**Comment by jamesyoungman** [comment]
1. nested_in() has no docs
2. An example which demonstrates the contrast between validate() and try_map().
3. Some methods have examples but no description, for example and_is(), not().
4. Motivating examples for boxed().

More generally, I've also had a lot of trouble with correctly declaring parser functions.  I do this in order to be able to unit-test parts of my parser.  But getting the ... correct in the -> impl Parser<...> is pretty tough.   Some of the "trait bounds not met" errors that can result are quite hairy.  And often these result in the simplest mistakes, for example using choice((x, y, z)) where choice(x(), y(), z())) was meant.

I had real trouble getting Chumsky to integrate well with Ariadne.   What's needed there is a clearly-explained non-trivial example.   I assume the reason that doesn't already exist is that neither crate wants to depend on the other.  But there must be some solution to that.

One last piece of feedback, and please don't take this as unkindly meant, there are some plans described in the "Future Directions" section, but those things are entirely uninteresting to me.  The areas I think need work are around usability and ergonomics.   I'm not saying that the existing plans are not good ideas, it's just that perhaps folks on the inside can underestimate the size of the barriers to adoption that exist.

**Comment by zesterer** [comment]
> The areas I think need work are around usability and ergonomics.

I completely agree! Chumsky has turned into a fairly powerful crate with a lot of bells and whistles recently. I'd love to be able to improve the compiler errors it generates. Unfortunately, there's not a huge amount that we can do from our side: there are almost no good ways to control the behaviour of Rust's trait solver. Those techniques that do exist are documented already [here](https://github.com/zesterer/chumsky/blob/49f1b84f8dbdf15a06cb091bcf8e88f286dfe753/guide/getting_started.md#compiler-errors). I'm hoping that as chumsky gains adoption, it'll encourage the compiler devs to find ways to make them more approachable. In fact, this is already happening: I've reason to believe that recent changes to the way long type errors are displayed by the compiler were, in part, inspired by several bug reports derived from chumsky users. There's definitely a lot more to be done though.

> One last piece of feedback, and please don't take this as unkindly meant, there are some plans described in the "Future Directions" section, but those things are entirely uninteresting to me.

The current README has not yet been properly updated for `1.0` (I'm currently working on that, on and off). All things in the 'Planned Features' section have actually already been implemented for `1.0`, as it happens.

The final thing I'd say is that `1.0` is still an alpha. Although it's pretty much ready from a functionality perspective, the same can't be said for documentation: that's my current priority and it's what I spend pretty much all of the free time that I have to throw at the project on right now. Before the final release of `1.0`, I plan to:

- Run through all existing documentation checking for correctness, adding meaningful examples to every non-trivial function
- Flesh out the guide with sections on errors and recovery, context-sensitive parsing, etc.
- Write a tutorial that shows the end-to-end process of developing a small programming language with chumsky (similar in nature to [Foo](https://github.com/zesterer/chumsky/blob/49f1b84f8dbdf15a06cb091bcf8e88f286dfe753/tutorial.md), but with more detail and use of more advanced crate features)

Annoyingly I can't really put a timeline on this right now (the past month has been unexpectedly busy for me), but it shouldn't be too long yet.

**Comment by CraftSpider** [comment]
I did hit `nested_in` in my PR, but I'll also try to add some comments to the other functions you called out! The other thing I did was try to add more interlinking and explanation of the major traits - `Parser` has a bit more description of its generics, and the associated traits both try to provide more explanation of what they 'mean', but also include examples of common implementing types users would care to use.

As zesterer mentioned, it's unfortunate that rust doesn't really allow controlling the error messages for unimplemented traits better. For now I think the best that can be done is trying to make the documentation clean. As someone who spends a long time in the guts of chumsky, I've started to be able to better intuit what the errors are trying to say - I wonder if I can try some common mistakes and see if there's any advice I can distill into a set of 'ignore all this, what you care about is this part' rules.

**Comment by jamesyoungman** [comment]
One other area that could benefit from better documentation is the ConfigParser.   This gets a one-line description which doesn't really help the reader understand what problems this feature solves[1] or how to use it.  The example (examples/indent.rs) comes with no explanation at all, and certainly I stared at it for several minutes without really being able to work out what was going on.

I'd suggest some longer-form writing to explain to, well, everybody, what should go in the parser's state versus what should be dealt with by configuration.   Perhaps include an example that uses both to clearly explain how each is used.

[1] it's a truism of technical writing that before one describes a technology, one should first explain the problem that it is intended to solve.

**Comment by CraftSpider** [comment]
I'll try to hit that too. Most of these single-line documentations are my fault - rather than have nothing, I put single-liners in knowing that zesterer intends to do a documentation pass before release, and the single-line was better than nothing at all. Now I'm going back and fixing my own TODO items :P

**Comment by CraftSpider** [comment]
(If you want to take a look at the PR I started #412, I started trying to explain 'State' vs 'Context' in the `ParserExtra` docs, with the idea that one affects the output of the parser but not what it accepts, and the other affects what it accepts, and thus implicitly the output, but not directly via map or such)
