### ISSUE TITLE
Broken links in the guide

### ISSUE THREAD

**Issue by FireFragment** [zesterer/chumsky#405]
In [`guide/intro.md`](https://github.com/zesterer/chumsky/blob/main/guide/intro.md), the links to chapters of the guide are broken

**Comment by zesterer** [comment]
Eurgh, whoops. Thanks for pointing this out!

**Comment by zesterer** [comment]
This should be fixed now.

**Comment by DariusCorvus** [comment]
It seems that the links are still broken
