### ISSUE TITLE
Missing `SeparatedBy::at_most(n)` and add a `exactly(n)` for `SeparatedBy` & `Repeated` ?

### ISSUE THREAD

**Issue by bew** [zesterer/chumsky#41]
I see `at_least` but not `at_most`.

Usecase: For AoC day04 (https://adventofcode.com/2021/day/4)
The input has game boards, each of 5 lines of numbers separated by a newline.

I've made a parser for a line of numbers and want to do `board_line.separated_by(newline).at_most(5)`

Other option that would work for me (be better w.r.t the spec of the input) is a `SeparatedBy::exactly(n)` that would set both `at_least` and `at_most` to the same value.
--> In this case, also add it to `Repeated` ?

What do you think?

**Comment by zesterer** [comment]
> What do you think?

Absolutely! I've just implemented all of these (`SeparatedBy::at_most`, `Separated::exactly`, and `Repeated::exactly`) in 1c981da. They'll be included in the next stable release. Thanks for the suggestion!

**Comment by bew** [comment]
Perfect :ok_hand:
