### ISSUE TITLE
Compile times

### ISSUE THREAD

**Issue by willothy** [zesterer/chumsky#415]
I'm struggling with rapidly increasing compilation times when implementing a recursive expression parser. It's based on the expr parser in the `nano_rust` example, but adds layers of `foldl` for each operator type / precedence.

For each operator I add, compilation times increase **significantly**. With just the `unary`, `additive` and `multiplicative` ops, the project compiles in seconds. However, by the time I've added all operators, it will not compile after several minutes of waiting on a Ryzen 5800x.

The code I'm referencing is a bit messy as I'm still getting used to chumsky, but you can see it [here](https://github.com/willothy/crane-lang/blob/191cb9b2d087ead138887443609087df99383192/crane-parse/src/lib.rs#L369)  / [here](https://github.com/willothy/crane-lang/pull/2#pullrequestreview-1416022732)

Any tips on how to improve compilation times here, or how to split the operator parser closures into their own separate functions? 

Thanks

**Comment by willothy** [comment]
Edit: After trying some things and looking through other people's projects using Chumsky, I discovered that I can use `Parser::boxed` to allow implementing the op functions separately from the expr parser function. I then use a loop instead of repeated `foldr`'s to create the parsers, like this:
```rust
let bin_parsers = [
    multiplicative().boxed(),
    additive().boxed(),
    bitshift().boxed(),
    relational().boxed(),
    equality().boxed(),
    bit!(And).map(|_| BinaryOp::BitwiseAnd).boxed(),
    // etc ...
];

let mut binary = unary.boxed();

for parser in bin_parsers {
    binary = binary
        .clone()
        .foldl_with_state(
            parser.clone().then(binary).repeated(),
            |lhs, (op, rhs), state: &mut ParserState| {
                state
                    .current_unit_mut()
                    .new_expr(Expr::BinaryOp { lhs, op, rhs })
            },
        )
        .boxed();
}

binary
```

I can't exactly explain why, but this brought me back to compiling in seconds. Most likely due to IR generation bloat / monomorphization as some other issues have mentioned.

Closing this since my specific issue is resolved, but definitely would be worth documenting use cases that will result in slow compile times, and related workarounds.

**Comment by zesterer** [comment]
Yep, `boxed` uses dynamic dispatch and so results in the compiler performing less trait solving work. Also see [the guide](https://github.com/zesterer/chumsky/blob/main/guide/getting_started.md#advice) for more information on reducing compilation times :)
