### ISSUE TITLE
Parsing into Cow

### ISSUE THREAD

**Issue by archseer** [zesterer/chumsky#423]
I've been taking a look at the JSON escape parsing from the examples: https://github.com/zesterer/chumsky/blob/ff71203eba21d3657285145910d9e4662fe58e75/examples/json.rs#L39-L70

From what I could tell the `escape` combinator ends up only matching the escapes and not actually substituting them (because of the ignores).

How could this parser be modified to substitute the escapes and map to a `Cow<str>` (`&str` for strings with no escaping, `String` for strings that require substitution)? Would this be better done in a second pass after matching? (e.g. using a simpler combinator from the benchmarks, then post-processing)

**Comment by archseer** [comment]
(Great crate by the way! The 1.0 API has been fun to use :) )

**Comment by zesterer** [comment]
One approach might be to try parsing a string without escaped, emitting a `Cow::Borrowed` and then have a more expensive fallback pattern that does permit escapes that produces a `Cow::Owned`, then invoke them one after the other like `unescaped.or(escaped)`.

**Comment by Zij-IT** [comment]
This issue good to be closed? @archseer

**Comment by zesterer** [comment]
Yep, I think it's fair to say that this is pretty much solved.
