### ISSUE TITLE
(Question) Escaping nested input

### ISSUE THREAD

**Issue by MariaSolOs** [zesterer/chumsky#428]
Hello again 🙃
I've been struggling quite a bit while writing a parser that can handle the following:

- Expressions inside single quotes (easy part).
- Nested expressions are allowed, but it requires the inner quotes to be escaped (tricky part).

I've been trying to address the second point with something like `expr.nested_in(just('\\').ignore_then("'").or(none_of("'")).repeated().collect().padded_by(just("'")))`, but then the problem is that `expr` takes a `&str`, but `collect` will only allow me to map the escaped input to a `String`.

Mainly I'm looking for something like `slice`, but that it respects the escaping I performed. Is there a clean way to do this?

Sorry for the newbie question, I've just been stuck on this one for a while 😅

**Comment by zesterer** [comment]
It seems like you might be using the wrong combinator here. `nested_in` is specifically for *inputs* that have nesting (for example, Rust-style [token trees](https://doc.rust-lang.org/beta/proc_macro/enum.TokenTree.html)). See the [`nested.rs`](https://github.com/zesterer/chumsky/blob/main/examples/nested.rs) example.

It's a bit hard to tell what behaviour you're looking for from the information you provided alone unfortunately. Could you give me a few examples of cases you want to be able to handle?

**Comment by MariaSolOs** [comment]
@zesterer thanks for the reply! Okay so I just realized I used single quotes in the description when I was actually thinking about backticks. I shouldn't write GitHub issues at 1am lol.

The full story is that I'm trying to write a lexer for bash, using [these rules for token recognition](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03). I'm struggling with command expansions of the form ``` `command` ```, since nested expansions are allowed but the inner backticks are escaped, and so my inner delimiters for the recursion are different from the outer ones.

**Comment by zesterer** [comment]
So this seems to be a context-sensitive rule in bash. You'll probably want to pass down context about the delimiter that should be used using the `then_with_ctx` and `configure` combinators. Take a look at [`indent.rs`](https://github.com/zesterer/chumsky/blob/main/examples/indent.rs) for an example of how to use these combinators to introduce context sensitivity. In `indent.rs`, the context is 'the amount of indentation that corresponds to the current block', whereas in your case the context is 'the delimiter that should be used for representing command substitutions'.

**Comment by MariaSolOs** [comment]
@zesterer Got it, thanks for the clues! I'll close this now since it's not a bug and I don't want to clutter your issues.
