### ISSUE TITLE
Implement Parser for either::Either

### ISSUE THREAD

**Issue by zesterer** [zesterer/chumsky#431]
Very useful for building up parsers at runtime without `.boxed()`.

**Comment by Zij-IT** [comment]
So here's the question: Should this be handled by `chumsky`, or should a pull request be made for `either`, which contains the implementation?

I only know from `serde` that it provides the traits and has the other libraries have the impls instead of trying to maintain those itself.

**Comment by zesterer** [comment]
I would say that this is *probably* something to put behind an `either` feature flag in chumsky. That said, I think `itertools` also has its own implementation of `Either` :upside_down_face: so we can't please everybody. The former is pretty common, however.
