### ISSUE TITLE
use of undeclared crate or module `extra`

### ISSUE THREAD

**Issue by vrindisbacher** [zesterer/chumsky#432]
I just finished up the Chumsky tutorial (great stuff btw), but I'd like to play around with the errors a bit more. I see that for nano_rs and json, `Rich` is used. However, I can't seem to import it (or find the declaration in the source). My `Cargo.toml` has `chumsky = "0.9.2"` as dependency

**Comment by CraftSpider** [comment]
The examples on the repository are for version `1.0.0-alpha.1` and above - they've been updated in step with the next planned release.

If you look at the `0.9` release tag, it should have a link to the tagged commit, and if you look at the repository for that commit the examples should match the version you're using.
