### ISSUE TITLE
`text::keyword` won't accept a newline

### ISSUE THREAD

**Issue by MultisampledNight** [zesterer/chumsky#436]
## Context

I have a keyword (`endsnippet` from UltiSnips snippet files) that must always be at the beginning of a line, and fully on its own, functioning as a signal for ending verbatim input. Since the grammar ensures that it cannot be on the first line, I thought I could just avoid parsing the ending `\n` of the line before, in order to consume it in one go instead.

## MVCE

Using `1.0.0-alpha.4`:

```rust
use chumsky::prelude::*;

fn main() {
    let parser = text::keyword::<_, _, _, extra::Err<Simple<_>>>("two\nfold");

    dbg!(parser.parse("two\nfold"));
}
```

### Expected

```
[src/main.rs:6] parser.parse("twofold") = ParseResult {
    output: Some(
        "twofold",
    ),
    errs: [],
}
```

### Actual

```
[src/main.rs:6] parser.parse("two\nfold") = ParseResult {
    output: None,
    errs: [
        found end of input at 0..3,
    ],
}
```

### Workaround

Can be done by manually chaining the individual lines with `.then` and applying a `.map` afterwards, `format!`ting them all together again.

## Thoughts

Stepping through to `src/text.rs:421` with lldb, seemingly `try_map` only ever receives the text until the next newline:

```rust
(lldb) b text.rs:421
Breakpoint 1: where = chumsky-hell`chumsky::text::keyword::_$u7b$$u7b$closure$u7d$$u7d$::h8d3abaa56c5527f2 + 74 at text.rs:421:16, address = 0x000000000001082a
(lldb) r
Process 124730 launched: '.../target/debug/chumsky-hell' (x86_64)
Process 124730 stopped
* thread #1, name = 'chumsky-hell', stop reason = breakpoint 1.1
    frame #0: 0x000055555556482a chumsky-hell`chumsky::text::keyword::_$u7b$$u7b$closure$u7d$$u7d$::h8d3abaa56c5527f2(s="two", span=SimpleSpan<usize, ()> @ 0x00007ffffffedfd8) at text.rs:421:16
   418 	{
   419 	    ident()
   420 	        .try_map(move |s: &C::Str, span| {
-> 421 	            if s == keyword.as_ref() {
   422 	                Ok(())
   423 	            } else {
   424 	                Err(Error::expected_found(None, None, span))
(lldb) p s
(&str) $0 = "two" {
  data_ptr = 0x000055555559f819 "two\nfold[src/main.rs:6] parser.parse(\"two\\nfold\") = \n"
  length = 3
}
```

(sidenote: this library is absolutely great! the name of the crate I've created for testing this only reflects my frustrations, lol)

**Comment by MultisampledNight** [comment]
Two seconds after clicking `Open` I realized how stupid this is. `text::keyword` uses `text::ident` which deliberately only accepts `[a-zA-Z_][a-zA-Z0-9_]*`. Nevermind.

**Comment by zesterer** [comment]
It might be worth us adding a `debug_assert` to `keyword` that ensures that the string is actually a valid identifier.

**Comment by zesterer** [comment]
I've added this in fce54bb.
