### ISSUE TITLE
Normalize spelling of memoization/memoisation

### ISSUE THREAD

**Issue by bglw** [zesterer/chumsky#444]
Currently the crate feature is `memoization`, but the function & type are `memoised` / `Memoised`. I don't have much of a preference either way — but it would be good to have them match 🙂

https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/src/lib.rs#L735-L736

**Comment by zesterer** [comment]
Ah, the pains of being a British developer on a US-oriented internet! Seems like some typos slipped through. I'll put this on my todo list.

**Comment by bglw** [comment]
I hear ya from New Zealand — not a typo to me 😎

**Comment by Zij-IT** [comment]
As one of those US people, I am surprised I didn't catch the discrepancy, because "memoised" is definitely wrong ;)

**Comment by Zij-IT** [comment]
Closable :)
