### ISSUE TITLE
unable to finish tutorial

### ISSUE THREAD

**Issue by fdncred** [zesterer/chumsky#446]
I've been trying to get through the awesome tutorial but I'm been unable to get past [parsing lets](https://github.com/zesterer/chumsky/blob/main/tutorial.md#parsing-lets).

I assumed, like in other issues, that i should use `chumsky = "1.0.0-alpha.1"` but that gave errors, so I tried the main repo branch like `chumsky = { git = "https://github.com/zesterer/chumsky", branch = "main" }` and that's closer but it still gives this error:
```
❯ cargo r -- .\test4.foo                                                                                                                          16:00:11  
   Compiling foo-chumsky v0.1.0 (C:\Users\username\source\repos\forks\foo-chumsky)
error[E0220]: associated type `Error` not found for `chumsky::Parser<'static, char, Expr>`
  --> src\main.rs:42:49
   |
42 | fn parser() -> impl Parser<'static, char, Expr, Error = Simple<'static, char>> {
   |                                                 ^^^^^ associated type `Error` not found

For more information about this error, try `rustc --explain E0220`.
error: could not compile `foo-chumsky` (bin "foo-chumsky") due to previous error
```

Any tips on how to proceed?

**Comment by zesterer** [comment]
The tutorial was written for 0.9 and has not yet been updated for 1.0 (despite the claim at the top of the tutorial that it's kept up to date with the master branch). However, the [`foo.rs` example](https://github.com/zesterer/chumsky/blob/main/examples/foo.rs) (which pretty much just contains the full final code from the tutorial) has been updated, so you could probably use that as a reference for now.

**Comment by fdncred** [comment]
Thank you!
