### ISSUE TITLE
Clarification around Span::Context vs input::WithContext

### ISSUE THREAD

**Issue by bglw** [zesterer/chumsky#447]
I've been looking for the best way to implement tracking filename/source info _(with `1.0.0-alpha.4`)_ and I'm a little confused between the `Span::Context` associated type, and the `input::WithContext` method.

The former states **_This is usually some way to uniquely identity the source file_** which sounds like what I'm after, but I can't see how to achieve using it without implementing the `Input` trait (which is sealed). For instance, I'm first lexing over an input of `&str`, which has a fixed impl of `type Span = SimpleSpan<usize>` (thus `Context = ()`).

Alternatively I see `input::WithContext`, which gives me `(FileContext, SimpleSpan<usize>)` as the span. This seems harder to wrangle in a two-pass parse, though if this is the canonical way then I'll proceed. It does leave me a little confused though, why the `Span::Context` also exists.

Alternative to all of the above, I'm missing something very obvious or I'm sitting on some rough edges of the alpha! In any case, I would really appreciate some loose guidance on the direction I should be looking.

_(Happy to provide sample code, omitting since it's of dubious use, as I don't quite how I should be approaching this in the first place. In abstract, lexing `&str` into some `TokenTree`, and then parsing that into some final `AST` that should contain `&str` spans)_

**Comment by fowenix** [comment]
Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/src/lib.rs#L2686) for an example of [`Input::with_context`](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/input/trait.Input.html#method.with_context)

Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L47) to view an example lexer, that returns span with the lexed token.

Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L587) to view where that lexer output is spanned with the spans in the lexer output.

Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L180) to view a type alias of [`SpannedInput`](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/input/struct.SpannedInput.html), you would need to use that in your parsers like [this](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L197)

**Comment by bglw** [comment]
I have been following these examples (and they somewhat align what I have built out), though my question sort of revolves around what these two example would look like together.

> Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/src/lib.rs#L2686) for an example of [Input::with_context](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/input/trait.Input.html#method.with_context)

This is the path I described as "harder to wrangle". Maybe erroneously so! I haven't fully tried it yet. Thinking through how I would wire up that span tuple into the `nano_rust` example is what prompted me to pose the question. It's definitely doable, but my main question revolves around

> Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L47) ...
> Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L587) ...
> Click [here](https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L180) ...

The `nano_rust` example is invaluable, but what I first reached for was changing:
https://github.com/zesterer/chumsky/blob/da41f156f45d12c27c94e7c93e18ea33514a0ed6/examples/nano_rust.rs#L10

to:
```rust
pub type Span = SimpleSpan<usize, MyContextStruct>;
```

since the `Span::Context` type seems like the most intuitive place for this to live. And that doesn't seem possible without changing the input type of the lexer itself away from `&str`.

***

I am going to carry on down the `Input::with_context` path and see how viable `(MyContextStruct, SimpleSpan<usize>)` is with a complex setup, so I'll have an update here before too long.

But I _would_ love to dig into whether `SimpleSpan<usize, MyContextStruct>` is possible instead. _(Unsealed `Input` trait? `&str` impl with a generic `type Span = S`? Unsure)_

**Comment by Zij-IT** [comment]
@zesterer 
This begs the question.

Is it purposeful that `Span<T, C>` is not constructible with `C != ()`, and that many trait impls are only implemented for `Span<T, ()>` and if so, why does it have `C`?

**Comment by bglw** [comment]
I have implemented the method I was reaching for in #448 — which somewhat serves as a way to construct a `Span<T, C>` by wrapping one of the impls for `Span<T, ()>`. Hopefully it at least spurs some discussion 🙂

**Comment by zesterer** [comment]
> @zesterer This begs the question.
> 
> Is it purposeful that `Span<T, C>` is not constructible with `C != ()`, and that many trait impls are only implemented for `Span<T, ()>` and if so, why does it have `C`?

Which traits are you talking about in particular? I think the only impl that could have its constraints weakened is `Debug`, that I can see.

I would definitely be happy to see a way to construct a `SimpleSpan` with `C != ()` though! The reason for this not existing yet is that `SimpleSpan` started off with no context parameter, but one was added later and API accomodations haven't yet been made.

**Comment by zesterer** [comment]
Regarding the original question: `Input::with_context` allows you to take a simple span, like a byte range, and annotate it with the context that the span relates to (such as the path of the file it refers to). It does this by turning the spans emitted by the input from `S` (the original span type, perhaps `Range<usize>` in your case) to `(C, S)` (i.e: the context + the byte span). If you take a look at [this impl](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/span/trait.Span.html#impl-Span-for-(C,+S)) you can see that span is implemented for `(C, impl Span)` so this is a valid span.

I do wonder whether `WithContext` should be generalised a bit though. It could easily become something like:

```rs
my_input
    .map_span(|byte_range| SimpleSpan::new(byte_range.start, byte_range.end, file_id))
```

Would this suit your use-case better?

**Comment by bglw** [comment]
```rust
my_input
    .map_span(|byte_range| SimpleSpan::new(byte_range.start, byte_range.end, file_id))
```

I like this also! Though for a generic wrapper, I'm not sure if it could return `byte_range` over any input. Looking at how I had to do the generic impl, it would probably be more like:

```rust
my_input
    .map_span(|input_span| SimpleSpan::new(input_span.start(), input_span.end(), file_id))
```

Where you get given what the span would be, and you can recreate or transform it. That would also give you:

```rust
my_input
    .map_span(|custom_span| custom_span.attach(file_id))
```

If you were using your own spans, and your custom span type had some `fn attach(self, file_id: _) -> Self` method.

It feels like maybe a little bit more of a headache having the closure? So my gut tells me it would be nice to have both `with_context` and `map_span` — but I'm not opposed to supporting _only_ `map_span` to reduce the maintenance.

**Comment by bglw** [comment]
Fast-follow: [commented here](https://github.com/zesterer/chumsky/pull/448#discussion_r1234457259). (`map_span` seems difficult to achieve)
