### ISSUE TITLE
Examples are outdated

### ISSUE THREAD

**Issue by CodesOtakuYT** [zesterer/chumsky#456]
Examples are outdated

**Comment by zesterer** [comment]
Which examples in particular?

**Comment by CodesOtakuYT** [comment]
all the examples I tried didn't work for me for some reason. one of the errors are about text ascii and parser lifetime, String, etc...

**Comment by zesterer** [comment]
All examples are checked by CI. What version of chumsky are you using? The current `main` branch is not compatible with older versions like 0.9.

**Comment by CodesOtakuYT** [comment]
The latest cargo version

**Comment by Zij-IT** [comment]
> The latest cargo version

@CodesOtakuYT - Zesterer was asking what version of the chumsky library you are using. The current branch (`main`) compiles all the of the examples that are currently in the example folder.

You can reproduce this by pulling the most recent version and running `$ cargo run --example indent`

**Comment by CodesOtakuYT** [comment]
> 

Oh thanks for the clarification!
