### ISSUE TITLE
Add `From<&[T; N]> for Stream<...>` impl

### ISSUE THREAD

**Issue by CraftSpider** [zesterer/chumsky#47]
Currently, there are `From` implementations on `Stream` for a variety of slice types. The one missing is `&[T; N]`. This is useful due to lack of coercion on generics making a call to `.parser(b"")` fail, as it's a reference to an array not a slice.

I'd be willing to PR it, if there's interest in it existing.

**Comment by zesterer** [comment]
Good idea! I'll add this for the next release.
