### ISSUE TITLE
SimpleSpan & Serde

### ISSUE THREAD

**Issue by 01mf02** [zesterer/chumsky#479]
In chumsky 0.9, I could serialise the output of my parser by `#[derive(Serialize, Deserialize)]` on my syntax tree.
Using chumsky 1.0.0-alpha.4, I cannot do this anymore, because [SimpleSpan](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/span/struct.SimpleSpan.html#) does not derive `Serialize`.
As a workaround, I tried to use `Range<usize>` as my `Span` type, because the [Span](https://docs.rs/chumsky/latest/chumsky/span/trait.Span.html#) documentation states that "Span is automatically implemented for [Range<T>](https://doc.rust-lang.org/nightly/core/ops/range/struct.Range.html)". Ok, let's try that:

~~~ rust
type Span = Range<usize>;
type Error<'a> = extra::Err<Rich<'a, char, Span>>;
~~~

But I cannot use this! Consider:

~~~ rust
fn foo<'a>() -> impl Parser<'a, &'a str, &'a str, Error<'a>> {
    todo()
}
~~~

This does not compile:

~~~
error[E0271]: type mismatch resolving `<&str as Input<'_>>::Span == Range<usize>`
~~~

Ok, so what's `<&str as Input<'_>>::Span`? [It's SimpleSpan](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/input/trait.Input.html#impl-Input%3C'a%3E-for-%26'a+str)! And there must be somewhere a constraint that dictates that the span of the input must be the same as the span type as chosen by the user.

So how can I use a `Span` such that I can serialise it?

**Comment by zesterer** [comment]
One option would be to add a `serde` feature to chumsky that derives these traits (I think this should probably be done regardless). Alternatively you can use [`Input::map_span`](https://github.com/zesterer/chumsky/blob/6f3371fb35d4cebc094185c1934141668b6fbb45/src/input.rs#L127-L137), although that's not yet been released on crates.io. You can still link to the git repository without too much issue though.
