### ISSUE TITLE
Feature Request: Implement ParserSealed for Choice<Vec<A>>

### ISSUE THREAD

**Issue by stefnotch** [zesterer/chumsky#484]
I want to build a choice parser at runtime, using some user-supplied tokens.
However, it doesn't seem like that's possible with the latest chumsky version
https://github.com/zesterer/chumsky/blob/10dad10f6a9254456bc56b91d2f0763427d7ddec/src/primitive.rs#L841

I could instead use a number of chained .or() parsers, but that might not be an ideal solution.

Background info why I even want this in the first place:
I'm writing an extensible math parser. Extensible, because I cannot possibly cover all areas of mathematics. At the very least, users should be able to define new symbols, like saying `lim` is a prefix operator and not a funnily named variable. Which would translate to `choice(vec![lim parser, variable parser, other parsers])`

**Comment by zesterer** [comment]
This seems like a sensible thing to do. If you're interested in contributing a PR, it should be possible to pretty much just duplicate the impl that already exists for `[A; N]` and swap the types out. If not, I can put it on my backlog to do at some point.
