### ISSUE TITLE
IntoIter combinator unnecessarily triggers infinite loop checks in other combinators such as foldr.

### ISSUE THREAD

**Issue by zyansheep** [zesterer/chumsky#500]
There are debug mode checks for infinite loops in various combinators which make sure the input offset advances each loop. 

The into_iter() combinator doesn't necessarily consume tokens as it generates outputs, which triggers these checks unnecessarily.

Not sure how this can be fixed in any elegant manner, but there are possible bodgy workarounds such as providing dedicated impls for IntoIter as a special case. Might require specialization for that though.

**Comment by Zij-IT** [comment]
Do you by chance have a minimal reproducable example?

**Comment by zesterer** [comment]
The only good way I can see to avoid the issue is to have some sort of associated constant/flag on `IterParser` that allows the consumer to communicate that not making progress during iteration is normal.

**Comment by zesterer** [comment]
Actually, that turned out to be incredibly easy to fix, see 18404e1.
