### ISSUE TITLE
Heavyweight vergen

### ISSUE THREAD

**Issue by stefnotch** [zesterer/chumsky#503]
So I updated my chumsky, and noticed that my lockfile suddenly gained around 1000 new lines. 
Apparently vergen causes the extra dependencies. https://github.com/zesterer/chumsky/commit/136f882b46cdcbd08354a98210da86d322383b84

![image](https://github.com/zesterer/chumsky/assets/10220080/a072561e-c88d-4749-b380-7a8f07eef399)

I'm not worrying too much about it, since the (from scratch) compile times for me are still pretty fast, but I figured I'd let you know.

**Comment by stefnotch** [comment]
It might be possible to put vergen into its own feature, and then use https://docs.rs/about/metadata to specify `--features ...`.
That way, vergen would only do its magic on docs.rs.

(The alternative of using `cfg(doc)` doesn't seem to be a thing at the moment.)

The ideal solution would probably be https://github.com/rust-lang/docs.rs/issues/132

**Comment by zesterer** [comment]
Thanks, this is useful to know. I'll try to get some time to sort this out in a nicer way when I'm back in a week.

**Comment by stefnotch** [comment]
Ooh, chumsky already uses a funny trick to make `cfg(docsrs)` work. Then making vergen an optional dependency that only gets activated when docsrs is a thing should work.
