### ISSUE TITLE
add `into_span()`, a parser which simply returns the span

### ISSUE THREAD

**Issue by pickx** [zesterer/chumsky#505]
for a program I'm currently working on, I often need to save the span of a parse, but I don't care about the actual output. this means I have lots of `.map_with_span(|_, span| span)` calls littering the code.
it would be nice if I could instead replace all those calls with something concise like `into_span()`.

**Comment by Zij-IT** [comment]
I believe this is already in `main` in the form of [`Parser::to_span`](https://github.com/zesterer/chumsky/blob/771cfcb8db72388cf83679e74df9f7b75fe49e2e/src/lib.rs#L655C1-L663C6)

**Comment by zesterer** [comment]
Closing this since the relevant combinator will be in the next alpha release.
