### ISSUE TITLE
Use case: `InputRef::skip_n` or equivalent

### ISSUE THREAD

**Issue by safasofuoglu** [zesterer/chumsky#508]
I'm experimenting with an extension to parse floats using the `lexical` crate. The advantage of `lexical::parse_partial` is that is lexes+parses at one shot, starting from the given position in the slice, until the end of the float representation. This way, it performs better even compared to lexing with logos (30% in my case with float-only data).

`lexical::parse_partial` returns a value along with the number of bytes read. Ideally, I would tell the input to skip that many bytes, but currently it's not possible.  Looping over `skip()` does not optimize well. A dirty attempt to implement `skip_n` shows 20% improvement in my case with float-only data.

```rust
struct LexicalFloat;

impl<'a, E> ExtParser<'a, &'a [u8], f32, E> for LexicalFloat
where
    E: extra::ParserExtra<'a, &'a [u8]>,
{
    fn parse(&self, inp: &mut InputRef<'a, '_, &'a [u8], E>) -> Result<f32, E::Error> {
        let before = inp.offset();
        
        match lexical::parse_partial(inp.slice_from(inp.offset()..)) {
            Ok((val, len)) => {
                // for _ in 0..len {
                //     inp.skip();
                // }
                inp.skip_n(len);
                Ok(val)
            }
            Err(_) => Err(E::Error::expected_found(
                [],
                inp.next_maybe().as_deref().copied().map(Into::into),
                inp.span_since(before),
            )),
        }
    }
}
```

**Comment by safasofuoglu** [comment]
Another attempt that doesnt optimize well:
```rust
let _ = inp.parse(any().repeated().at_most(len));
```

**Comment by zesterer** [comment]
FWIW the `main` branch does support parting numbers with `lexical` (see the docs of the `number` module) and this will be included in the next alpha release.

There is an internal `InputRef::skip_bytes` that works for inputs that implement `SliceInput<Offset = usize>`, used by the `regex` and `lexical-numbers` features. However, it performs no validation and hence has the capacity to be unsound if exposed publicly (which reminds me: I need to mark it as `unsafe`).

I could probably implement a `Input::skip_n` method that's exposed via `InputRef` with a default unoptimised implementation that just called `next_maybe` repeatedly though. Would this suit your needs?

**Comment by safasofuoglu** [comment]
`lexical-numbers` on main hits the spot for me.

> I could probably implement a Input::skip_n method that's exposed via InputRef with a default unoptimised implementation that just called next_maybe repeatedly though. Would this suit your needs?

That's not any better than the two approaches I tried above. I was thinking about a specialized `AnyRepeated` that eats n bytes/tokens with a single range check. However, my use case seems to be already covered (optimized well), so I'd rather avoid speculation.

Thank you.
