### ISSUE TITLE
Add a Pratt parsing combinator

### ISSUE THREAD

**Issue by zesterer** [zesterer/chumsky#51]

**Comment by kevinbarabash** [comment]
Would this allow a person to embedded a Pratt parser for algebraic expressions within in a parent parser for a programming language?

**Comment by zesterer** [comment]
Yes, that would be the goal.

**Comment by kevinbarabash** [comment]
That sounds awesome.  I'm curious if you had any thoughts on what the API might look like.

I wrote a Pratt [parser factory](https://github.com/math-blocks/math-blocks/blob/master/packages/parser/src/factory.ts) in TypeScript a while ago.  It's surprisingly short, but it also doesn't support post-fix operators and there's some hardcoded logic in it, e.g. checking for unmatched parens.

I'm still relatively new to rust, but would be interested in helping out with this issue.

**Comment by zesterer** [comment]
I've not really had too many thoughts about it yet, to be honest. Perhaps I'll try some experimenting next week.

**Comment by zesterer** [comment]
`zero-copy` is getting a pratt parser combinator. See #288.

**Comment by Zij-IT** [comment]
Closable with #464
