### ISSUE TITLE
Get span in bytes instead of characters?

### ISSUE THREAD

**Issue by Timmmm** [zesterer/chumsky#512]
I was slightly surprised to find that `.map_with_span()` on a `char` parser returns values in units of `char`, not bytes. I guess it makes sense now that I think about it, but I'm so used to dealing with `Range<usize>` being byte ranges for Rust strings that I didn't really think about it.

The rest of my code uses UTF-8 byte ranges. Do you know of an elegant way to get the spans as UTF-8 byte ranges instead? I can think of a few less-than-ideal options.

**Comment by zesterer** [comment]
As of the (alpha) 1.0 releases, all spans are byte offsets. In 0.9 you can use byte offsets too by constructing `Stream` manually.

**Comment by Timmmm** [comment]
Aha, I upgraded to 1.0.0-alpha4 and that did the trick! If it helps you write the documentation, here were the things I had to change:

* `pub type Span = std::ops::Range<usize>;` -> `pub type Span = SimpleSpan<usize>;`
* `.chain()` -> `.then()`
* `.collect::<String>().map(` -> `.map_slice(`
* `.labelled(..)` -> Dunno, I just removed these for now... :-|
* `skip_then_retry_until([])` -> `skip_then_retry_until(any().ignored(), end())`
* `.parse_recovery(s)` -> `.parse(s)`
* `take_until(just("*/"))` -> `any().and_is(just("*/").not()).repeated()).then(just("*/"))` (feels like there's probably a better way here?)

I also couldn't figure out why this slightly modified `ident()` function doesn't work (it's supposed to allow `~` as a special identifier):

```
#[must_use]
pub fn ident<'a, I: ValueInput<'a> + StrInput<'a, C>, C: Char, E: ParserExtra<'a, I>>(
) -> impl Parser<'a, I, &'a C::Str, E> + Copy + Clone {
    any()
        // Use try_map over filter to get a better error on failure
        .try_map(|c: C, span| {
            if c.to_char().is_ascii_alphabetic() || c.to_char() == '_' || c.to_char() == '?' {
                Ok(c)
            } else {
                Err(Error::expected_found([], Some(MaybeRef::Val(c)), span))
            }
        })
        .then(
            any()
                // This error never appears due to `repeated` so can use `filter`
                .filter(|c: &C| c.to_char().is_ascii_alphanumeric() || c.to_char() == '_' || c.to_char() == '?' || c.to_char() == '\'')
                .repeated(),
        )
        .or(just('~'))
        .slice()
}
```

The error messages are *hard*! Documentation is generally excellent though, so it wasn't too bad an upgrade. Thanks for the great library! Don't think I'd go back to Nom or Tree Sitter.

**Comment by zesterer** [comment]
> here were the things I had to change:

Thanks! That's going to be quite useful when I finally get round to writing migration docs from 0.9 to 1.0.

>     * `.labelled(..)` -> Dunno, I just removed these for now... :-|

`labelled` still exists, but is behind the `label` feature flag for now.

>     * `take_until(just("*/"))` -> `any().and_is(just("*/").not()).repeated()).then(just("*/"))` (feels like there's probably a better way here?)

This is the current recommended approach, yes. It's unfortunate that it's more noisy, but `and_is` and `not` in combination are much more flexible than `take_until` (which ended up often being only a half solution for many problems). At some point I might try to take common patterns like this and put them into some sort of `escaped` combinator that makes this sort of thing a bit easier.

> I also couldn't figure out why this slightly modified `ident()` function doesn't work (it's supposed to allow `~` as a special identifier):

When you say that it doesn't work, what do you mean? Do you get compiler errors, or does it not parse a certain input correctly?

> The error messages are _hard_! Documentation is generally excellent though, so it wasn't too bad an upgrade. Thanks for the great library! Don't think I'd go back to Nom or Tree Sitter.

Thanks for your kind words! I definitely agree with regard to error messages: I'd really like to see Rust get better at these sort of diagnostics. I'm firmly of the opinion that it's possible to produce better results, but unfortunately I don't have enough knowledge of rustc to make the changes myself.

**Comment by Timmmm** [comment]
> labelled still exists, but is behind the label feature flag for now.

Aha, thanks!

> When you say that it doesn't work, what do you mean?

I get this compilation error:

```
error[E0277]: the trait bound `Just<char, _, _>: chumsky::private::ParserSealed<'_, _, (C, ()), _>` is not satisfied
    --> sail_parser\src\lib.rs:310:13
     |
310  |         .or(just('~'))
     |          -- ^^^^^^^^^ the trait `chumsky::private::ParserSealed<'_, _, (C, ()), _>` is not implemented for `Just<char, _, _>`
     |          |
     |          required by a bound introduced by this call
     |
     = help: the trait `chumsky::private::ParserSealed<'a, I, T, E>` is implemented for `Just<T, I, E>`
     = note: required for `Just<char, _, _>` to implement `Parser<'_, _, (C, ()), _>`
note: required by a bound in `or`
    --> C:\Users\Tim\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chumsky-1.0.0-alpha.4\src\lib.rs:1190:12
     |
1187 |     fn or<B>(self, other: B) -> Or<Self, B>
     |        -- required by a bound in this associated function
...
1190 |         B: Parser<'a, I, O, E>,
     |            ^^^^^^^^^^^^^^^^^^^ required by this bound in `Parser::or`

error[E0277]: the trait bound `Just<char, _, _>: chumsky::private::ParserSealed<'_, _, (C, ()), _>` is not satisfied
   --> sail_parser\src\lib.rs:311:10
    |
311 |         .slice()
    |          ^^^^^ the trait `chumsky::private::ParserSealed<'_, _, (C, ()), _>` is not implemented for `Just<char, _, _>`
    |
    = help: the trait `chumsky::private::ParserSealed<'a, I, T, E>` is implemented for `Just<T, I, E>`
    = note: required for `Just<char, _, _>` to implement `Parser<'_, _, (C, ()), _>`
    = note: required for `Or<Then<TryMap<chumsky::primitive::Any<_, _>, C, [closure@sail_parser\src\lib.rs:297:18: 297:30]>, Repeated<chumsky::combinator::Filter<chumsky::primitive::Any<_, _>, [closure@sail_parser\src\lib.rs:307:25: 307:32]>, C, _, _>, C, (), _>, Just<char, _, _>>` to implement `chumsky::private::ParserSealed<'_, _, (C, ()), _>`
note: required by a bound in `chumsky::Parser::slice`
   --> C:\Users\Tim\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chumsky-1.0.0-alpha.4\src\lib.rs:303:5
    |
303 |     ParserSealed<'a, I, O, E>
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Parser::slice`
...
416 |     fn slice(self) -> Slice<Self, O>
    |        ----- required by a bound in this associated function

error[E0277]: the trait bound `Just<char, _, _>: chumsky::private::ParserSealed<'_, I, (C, ()), E>` is not satisfied
   --> sail_parser\src\lib.rs:294:6
    |
294 | ) -> impl Parser<'a, I, &'a C::Str, E> + Copy + Clone {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `chumsky::private::ParserSealed<'_, I, (C, ()), E>` is not implemented for `Just<char, _, _>`
    |
    = help: the trait `chumsky::private::ParserSealed<'a, I, T, E>` is implemented for `Just<T, I, E>`
    = note: required for `Just<char, _, _>` to implement `Parser<'_, I, (C, ()), E>`
    = note: required for `Or<Then<TryMap<chumsky::primitive::Any<I, E>, C, [closure@sail_parser\src\lib.rs:297:18: 297:30]>, Repeated<chumsky::combinator::Filter<chumsky::primitive::Any<I, E>, [closure@sail_parser\src\lib.rs:307:25: 307:32]>, C, I, E>, C, (), E>, Just<char, _, _>>` to implement `chumsky::private::ParserSealed<'_, I, (C, ()), E>`
    = note: 3 redundant requirements hidden
    = note: required for `Slice<Or<Then<TryMap<chumsky::primitive::Any<I, E>, C, [closure@sail_parser\src\lib.rs:297:18: 297:30]>, Repeated<chumsky::combinator::Filter<chumsky::primitive::Any<I, E>, [closure@sail_parser\src\lib.rs:307:25: 307:32]>, C, I, E>, C, (), E>, Just<char, _, _>>, 
(C, ())>` to implement `Parser<'a, I, &'a <C as chumsky::text::Char>::Str, E>`
```

**Comment by zesterer** [comment]
The problem here is that the output types of `a` and `b` in `a.or(b)` need to match. In your specific case, you have:

```rs
any()
    .then(...) // Output type = (char, _)
    .or(just('~') /* Output type = char */)
    .slice()
```

You can see is mismatch here. An easy approach to solving this, since the output value gets thrown away anyway, is to just use `.ignored()` on both parsers to give them both an output type of `()`:

```rs
any()
    .then(...)
    .ignored() // Output type = ()
    .or(just('~').ignored() /* Output type = () */)
    .slice()
```

**Comment by Timmmm** [comment]
Ah that still didn't quite compile, but one of the compilation errors was complaining about `C: Char`, saying I should use `where` instead. Since I don't care about being that generic I just changed all the `C`s to `char` and it worked!
