### ISSUE TITLE
Labelling parsers doesn't work sometimes

### ISSUE THREAD

**Issue by zyansheep** [zesterer/chumsky#518]
The following code is a minimum repro. It seems that the label gets used only in certain situations for the keyword parser. This may also be the case for other parsers (like ident), but I'm not entirely sure.

```rust
fn test_label_parse(string: &str) -> ParseResult<&str, Rich<'_, char>> {
	let parser = keyword::<&str, char, &str, extra::Err<Rich<char>>>("first");
	parser.labelled("first").parse(string)
}

#[test]
fn label_test() {
	let uses_label = test_label_parse("[first");
	let incorrect = test_label_parse("firsd");
	uses_label.errors().for_each(|err|println!("{err}"));
	incorrect.errors().for_each(|err|println!("{err}"));
	panic!();
}
```

**Comment by zesterer** [comment]
@zyansheep Any chance you could try this with the latest commit? I've made some fixes that I'm hoping will address this.

**Comment by zyansheep** [comment]
Yoo, I don't remember what it was giving me before, but it seems to work as I'd expect now! Thanks!

Also, lmk on discord if you want me to PR my bodgy fix for the "multiple errors" fmt message where I just cram all the sub-error messages in to a string delimited by square brackets :)

**Comment by zesterer** [comment]
Woo, great to hear!

Regarding the multi-error thing, are you talking about `RichReason::Many`?

**Comment by zyansheep** [comment]
Yeah, I made a quick fix on my repo that kinda just lists out the suberrors so I could actually see them

**Comment by zesterer** [comment]
Hmm. I'm planning to remove `RichReason::Many` because I think it's misleading and probably unnecessary.

**Comment by tfachmann** [comment]
How are plans on removing `RichReason::Many`? I stumbled upon this as well as #474 and got highly confused by it. In my case it backtracked and found the following (after calling `err.into_reason()`):

```
Many([ExpectedFound { expected: ['r'], found: None }, Custom("No request or response given.")])
```

The custom error is produced in some `try_map()` and I expected it to just fail at this point with the custom error message. Could a workaround for my case be to mark it as somewhat unrecovarable? Or is that not possible / intended?

**Comment by zesterer** [comment]
Removing `RichReason::Many` would involve `Rich` making a decision about which error reason should dominate the others as part of the error merging process. I think a sensible hierarchy, from most most dominant to least dominant, is:

- `Custom(...)`
- `ExpectedFound { found @ Some(_), .. }`
- `ExpectedFound { .. }`

I can try doing this today.

**Comment by zesterer** [comment]
`RichReason::Many` has now been removed.
