### ISSUE TITLE
`.delimited_by()` should take parsers as arguments, not input tokens

### ISSUE THREAD

**Issue by p-e-w** [zesterer/chumsky#52]
This is another inconsistency I noticed when working with the API. `.separated_by()` takes a parser as a separator, so it makes sense to expect that `.delimited_by()` take parsers as delimiters.

This would for example enable `.delimited_by()` to express surrounding XML tags in `char` parsers, which consist of multiple characters, and can contain parsable attributes themselves.

**Comment by zesterer** [comment]
Ah, this is an inconsistency I've been meaning to fit for a while. It's hangover from the `0.3` days when `delimited_by` implicitly did error recovery. Thanks for the reminder, I'll add this to my todo list.

In the meantime, it's fairly easy to emulate this behaviour with `start.ignore_then(inner).then_ignore(end)`.
