### ISSUE TITLE
Pratt Parsing Error Recovery

### ISSUE THREAD

**Issue by stefnotch** [zesterer/chumsky#532]
So I'm happily using the pratt parsing for mathematics. After all, mathematics has a lot of operators, from $+$, $*$, $<$ to $\sum$, $\lim$, $\mapsto$, $\implies$.

And now I'm wondering how one would do rock solid error recovery with it. Ideally, I could convince the error recovery to work like this:

Normal case, no error recovery.
```
a+b*c gets parsed as (a+(b*c))
```

`?` is an unknown input.
```
a+?*c maybe gets parsed as (a+(error*c))
a*?+c maybe gets parsed as ((a*error)+c)
```

And leaving out an atom is also an error.
```
a+*c gets parsed as (a+(error*c))
a*+c gets parsed as ((a*error)+c)
```

Using an unknown input `??` where an operator is expected is an error. I'm not sure what the ideal error recovery option for those would be
```
a+b??c 
a*b??c 
```
And same thing probably applies to leaving out an operator.

**Comment by zesterer** [comment]
I think you can just use regular error recovery strategies (i.e: `Parser::recover_with`) for these cases by applying the strategy to either the atom parser or the operator parser.

**Comment by stefnotch** [comment]
Sounds good, I'll try that out and get a feel for how good the error messages are.
