### ISSUE TITLE
Extension parser API request

### ISSUE THREAD

**Issue by stefnotch** [zesterer/chumsky#535]
I have a few places where I'm getting the offset in an extension parser. Since the current API hides the details, I ended up resorting to this questionable workaround

```rust
fn get_position<'a, I: Input<'a>, E: ParserExtra<'a, I>>(
    inp: &mut InputRef<'a, '_, I, E>,
) -> I::Span {
    inp.parse(empty().map_with_span(|_, span| span))
        .unwrap_or_else(|_| panic!("should never happen"))
}
```

It might be nice to have a method that lets one get the underlying offset?

**Comment by zesterer** [comment]
You should just be able to do

```rs
inp.span_sinc(inp.offset())
```

to get the zero-width span that the next token starts at.

**Comment by stefnotch** [comment]
Oh, I clearly missed that one! Thank you very much
