### ISSUE TITLE
Intro links do not resolve

### ISSUE THREAD

**Issue by nullishamy** [zesterer/chumsky#536]
The links in [the intro doc](https://github.com/zesterer/chumsky/blob/main/guide/intro.md) do not resolve correctly.

**Comment by zesterer** [comment]
Are you viewing them via docs.rs?

**Comment by nullishamy** [comment]
I was viewing via GitHub but I don't believe that would make a difference?

**Comment by zesterer** [comment]
The guide is intended to be viewed through [docs.rs](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/guide/index.html) (by hosting them there, we get the ability to precisely control the version of things we link to, as well as having inline examples that can be tested with CI).

**Comment by zesterer** [comment]
To minimise future confusion, I've added a [`README.md`](https://github.com/zesterer/chumsky/blob/main/guide/README.md) to improve things :)

**Comment by nullishamy** [comment]
Looks good! That link does go to 1.0.0alpha4, instead of a newer version. Was that intentional?

**Comment by nullishamy** [comment]
As an aside, the `examples/` directory is sort of strange. It's built against the latest `main` build, but that isn't identical to the latest cargo release. Perhaps this should also be clarified in a similar way (if there is some better way to view the examples)?

**Comment by zesterer** [comment]
> Looks good! That link does go to 1.0.0alpha4, instead of a newer version. Was that intentional?

Yes, `1.0-alpha.4` is the latest version on crates.io.

> It's built against the latest main build, but that isn't identical to the latest cargo release

It's not identical (this is fairly standard, fwiw) but they are similar enough for (I think) most of the examples to just work. Make sure that you're depending on one of the 1.0 alpha releases instead of 0.9. 0.9 is pretty much in legacy maintenance mode at this point, 1.0 is a complete rewrite of the crate.

**Comment by nullishamy** [comment]
Oh, I see. My cargo pulled `0.9.2` (which I misremembered as `1.9.2`, hence my comment). I changed it to just pull from git directly and the examples work fine (needed to enable the `label` feature which took a little bit of figuring out, but nothing drastic).

This seems to be resolved now, thanks!
