### ISSUE TITLE
Interest on a parser for positive integers (vs. text::int)?

### ISSUE THREAD

**Issue by schneiderfelipe** [zesterer/chumsky#550]
I propose adding a parser for strictly positive integers to [`chumsky::text`](https://github.com/zesterer/chumsky/blob/91a77041dcd92e3a8d382098d1ae84e93421c2ba/src/text.rs) (below are implementation sketches based on version 0.9.2):

```rust
#[must_use]
pub fn pint<C: Character, E: Error<C>>(
    radix: u32,
) -> impl Parser<C, C::Collection, Error = E> + Copy + Clone {
    filter(move |c: &C| c.is_digit(radix) && c != &C::digit_zero())
        .map(Some)
        .chain::<C, Vec<_>, _>(filter(move |c: &C| c.is_digit(radix)).repeated())
        .collect()
}
```

(Suggested names: `positive`, `pint`, `pos_int`?)

It would also allow simplifying the current [`text::int` implementation](https://github.com/zesterer/chumsky/blob/91a77041dcd92e3a8d382098d1ae84e93421c2ba/src/text.rs#L333-L351):

```rust
#[must_use]
pub fn int<C: Character, E: Error<C>>(
    radix: u32,
) -> impl Parser<C, C::Collection, Error = E> + Copy + Clone {
    pint().or(just(C::digit_zero()).map(|c| core::iter::once(c).collect()))
}
```

**Comment by cylewitruk** [comment]
Perhaps simply `uint` or `int_unsigned` would suffice for naming?

**Comment by zesterer** [comment]
FWIW, the [`int`](https://github.com/zesterer/chumsky/blob/91a77041dcd92e3a8d382098d1ae84e93421c2ba/src/text.rs#L334-L351) parser only accepts positive integers (or zero) (the name is misleading, admittedly) Does this suit your needs?

**Comment by schneiderfelipe** [comment]
The idea is having something that rejects zero. `text::nat` perhaps?

**Comment by zesterer** [comment]
You can also do `int().and_is(just('0').not())` if you wish to reject `0`.

**Comment by schneiderfelipe** [comment]
> You can also do `int().and_is(just('0').not())` if you wish to reject `0`. However, I don't think that this is a common enough use-case that it warrants a distinct combinator in chumsky itself.

Awesome! I didn't know about `and_is`. It suits my use case perfectly. Thanks!
