### ISSUE TITLE
alpha-1.0.0-alpha.6 release broken?

### ISSUE THREAD

**Issue by Zij-IT** [zesterer/chumsky#560]
It appears as if the most recent alpha release is broken due to a fix that was made later on main. I've attached the error below!

```shell
error[E0308]: mismatched types
   --> /<PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chumsky-1.0.0-alpha.6/src/combinator.rs:259:43
    |
241 | impl<'a, A, I, O, E, F> ParserSealed<'a, I, O, E> for Filter<A, F>
    |                - this type parameter
...
259 |                     Some(util::Maybe::Val(out)),
    |                          ---------------- ^^^ expected associated type, found type parameter `O`
    |                          |
    |                          arguments to this enum variant are incorrect
    |
    = note: expected associated type `<I as input::Input<'_>>::Token`
                found type parameter `O`
help: the type constructed contains `O` due to the type of the argument passed
   --> /<PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chumsky-1.0.0-alpha.6/src/combinator.rs:259:26
    |
259 |                     Some(util::Maybe::Val(out)),
    |                          ^^^^^^^^^^^^^^^^^---^
    |                                           |
    |                                           this argument influences the type of `util`
note: tuple variant defined here
   --> /<PATH>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chumsky-1.0.0-alpha.6/src/util.rs:27:5
    |
27  |     Val(T),
    |     ^^^
help: consider further restricting this bound
    |
243 |     I: Input<'a> + <Token = O>,
    |                  +++++++++++++
```

I hope to be able to help later with the 1.0 release. Currently in the middle of my Bachelor's Thesis (which uses Chumsky :D), so I hope that I will be able to help after I am done with it! That's actually how I came across this error!

**Comment by zesterer** [comment]
Hmm, what version of the compiler are you using?

> Currently in the middle of my Bachelor's Thesis (which uses Chumsky :D)

Good luck, I hope it goes well! I'd be interested to hear about what you've been up to when you're finished with it.

**Comment by Zij-IT** [comment]
It occurs to me on both the most recent stable and most recent nightly:
- stable-x86_64-apple-darwin unchanged - rustc 1.73.0 (cc66ad468 2023-10-03)
- nightly-x86_64-apple-darwin installed - rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)

I don't think I'm doing anything dumb, but here's the toml bit
```toml
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
```

**Comment by zesterer** [comment]
Hmm, I can't seem to reproduce this.

```
joshua@archlinux ~/tmp> rustc +nightly --version                                                                (base) 
rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)
joshua@archlinux ~/tmp> rustup update nightly^C                                                                 (base) 
joshua@archlinux ~/tmp> cat chumsky.rs                                                                          (base) 
```cargo
[dependencies]
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
```

fn main() {}
joshua@archlinux ~/tmp> cargo +nightly -Zscript chumsky.rs                                                      (base) 
warning: `package.edition` is unspecified, defaulting to `2021`
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/home/joshua/.cargo/target/60/e1b8f38880dfe6/debug/chumsky`
```

**Comment by Zij-IT** [comment]
I'll close this for now, as I was able to fix it by using a local version, and I need to do that anyway for some additions that I made to the library that I use in my project.
