### ISSUE TITLE
Idea: conditonal parser, which takes a parser and a condition

### ISSUE THREAD

**Issue by dexterdy** [zesterer/chumsky#565]
I originally tried to implement the idea with `then_with` or `custom` and a captured value, but `then_with` won't work because I can't return two different parser types and `custom` doesn't provide the right interface. It would be very useful if you had a conditional parser, which takes a condition and a parser that outputs `O` and returns a parser that outputs `Option<O>`.

This would will allow us to write similar parsers without repeating a whole bunch of code, by putting the part that is different in a conditional parser.

**Comment by zesterer** [comment]
Perhaps `.filter(...)` is what you're looking for? You can do `a.filter(|a| a.is_foo())`. I think you might be a bit confused about how parser outputs work though: Fallibility is built in to a parser, if the filter closure returns `false`, then the parser just won't parse anything.

**Comment by zesterer** [comment]
Ah, are you trying to dynamically change the behaviour of your parser at runtime based on some configuration for the parser? I assumed that the condition was dependent on the output of the parser. In that case, there are a few approaches you can take:

1) Parsers can be dynamically dispatched, so you can do `if condition { a.map(Some).boxed() } else { empty().to(None).boxed() }` and this should type-check just fine (the parser in the `else` branch always succeeds while parsing no tokens)

2) Use `custom` like so:

```
custom(|inp| if condition { inp.parse(a).map(Some) } else { Ok(None) })
```

this approach avoids the dynamic dispatch of the previous approach.

**Comment by dexterdy** [comment]
Ah yes! Thank you those are exactly what I need
