### ISSUE TITLE
when use tokio::spawn  i meet problem anyone can help

### ISSUE THREAD

**Issue by LinYUAN-code** [zesterer/chumsky#574]
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "127.0.0.1:8080";
    let listener = TcpListener::bind(addr).await?;
    println!("mysql running on {}", addr);

    loop {
        let (mut socket, _) = listener.accept().await?;
        println!("connected {:?}", socket);
        tokio::spawn(async move {
            let mut buf = [0; 1024];
            let mut command_buffer = String::new();

            let parser = Arc::new(Mutex::new(gen_parser()));
            loop {
                let mut buffer = String::new();

                match socket.read(&mut buf).await {
                    // socket closed
                    Ok(0) => return,
                    Ok(n) => command_buffer.push_str(from_utf8(&buf[0..n]).unwrap()),
                    Err(e) => {
                        eprintln!("failed to read from socket; err = {:?}", e);
                        return;
                    }
                };
                while let Some(index) = command_buffer.find(';') {
                    let command = command_buffer.as_str()[0..=index].to_string();
                    command_buffer = command_buffer.as_str()[(index + 1)..].to_string();

                    println!("{:?}", parser.lock().await.parse(command));
                    if let Err(e) = socket.write_all("detect command".as_bytes()).await {
                        eprintln!("failed to write to socket; err = {:?}", e);
                        return;
                    }
                }
            }
        });
    }
}
```

error: 
future cannot be sent between threads safely
within `impl chumsky::Parser<char, Statement, Error = Simple<char>>`, the trait `Send` is not implemented for `Rc<recursive::OnceCell<Box<(dyn chumsky::Parser<char, Expr, Error = Simple<char>> + 'static)>>>`

**Comment by wackbyte** [comment]
I think this requires you to enable the `sync` feature flag for chumksy.

**Comment by LinYUAN-code** [comment]
> I think this requires you to enable the `sync` feature flag for chumksy.

How could i do this? sor, i am new to rust.

**Comment by wackbyte** [comment]
In your Cargo.toml, you can enable feature flags on a dependency by

```
[dependencies]
chumsky = { version = "x", features = ["sync"] }
```

**Comment by zesterer** [comment]
Be aware that the `sync` feature will likely require some kind of revising before `1.0` is stable. See https://github.com/zesterer/chumsky/issues/543 for more information. It's not yet clear whether that revision will be breaking or not.

**Comment by nothendev** [comment]
I don't think the parser lock is even needed here, you could just have an Arc of the parser or you could just not store it and execute gen_parser inline, you won't even need the sync feature

**Comment by zesterer** [comment]
Unfortunately many parsers (like `Recursive`) are not `Send + Sync` because they use `Rc` internally. I do think that this requirement could be strengthened without issue though, since the added cost of an atomic increment would only apply on parser creation. That said, `Recursive` specifically might require some sort of lock internally due to the behaviour of `.define(...)`, although interestingly #123 might actually provide a solution to this.
