### ISSUE TITLE
Crashed while parsing markup text

### ISSUE THREAD

**Issue by kalxd** [zesterer/chumsky#588]
Hi all,
I am trying write a very simple parser for text likes markdown, here is my code:

```rust
use chumsky::extra::Err;
use chumsky::prelude::Rich;
use chumsky::IterParser;
use chumsky::{
    primitive::{just, none_of},
    Parser,
};

#[derive(Debug)]
enum Post<'a> {
    Topic(&'a str),
    Lit(&'a str),
}

const INPUT: &'static str = "abc#abcxx#";

fn test<'a>() -> impl Parser<'a, &'a str, Vec<Post<'a>>, Err<Rich<'a, char>>> {
    let lit = none_of("#").repeated().to_slice().map(Post::Lit);

    let topic = none_of("#")
        .repeated()
        .delimited_by(just('#'), just('#'))
        .to_slice()
        .map(Post::Topic);
    topic.or(lit).repeated().collect()
}

fn main() {
    dbg!(test().parse(INPUT));
}
```

I wanna parse `#<words>#` into `Post::Topic`, then the words out of  pair `#` would be `Post::Lit`.
so running the code, it is crashed.

```bash
thread 'main' panicked at /home/kalxd/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/chumsky-1.0.0-alpha.6/src/combinator.rs:1941:21:
found Collect combinator making no progress at src/main.rs:25:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

How to fix it? do I misunderstand primitive methods?
basic information:
* rustc: 1.75.0
* chumsky: 1.0.0-alpha.6
* OS: debian bookworm

thanks a lot.

**Comment by Zij-IT** [comment]
This happens because `topic` would happily parse an empty string. It's then being `repeated` a couple lines later, which means that it will infinitely parse `""` as `[Post::Topic(""), ...]`. To stop this, require that the topic have a length of at least 1 by adding `.at_least(1)` after the first `.repeated()`

**Comment by kalxd** [comment]
Great, it works, thanks again.

by the way, is there a method or a way  similar to  `take_while` of `nom`?

**Comment by zesterer** [comment]
Yes, `any().filter(|c| c.passes_condition()).repeated()` will do that.

**Comment by kalxd** [comment]
Thanks, that is what I looking for.
