### ISSUE TITLE
Question: Using `map_with` to get spans

### ISSUE THREAD

**Issue by nouritsu** [zesterer/chumsky#594]
I have the code
```rs
let stmt_declare = just(Token::Int)
        .then(ident)
        .map_with(|(ty, ident), e| (ty, (ident, e.span())))
        .then(just(Token::Equals).ignore_then(expr()).or_not())
        .then_ignore(just(Token::Semicolon))
        .map_with(|((_ty, ident_and_span, expr_and_span), e| (Stmt::Declare(ident_and_span, expr_and_span), e.span()))
        .boxed();
```
Here, in the `map_with` closure, `e.span()` gives me the span of `Token::Int` and the parsed identifier. Is there a way to only get the span of the parsed identifier without ignoring the type, which is to be used in the second `map_with`?

Basically in the code -
```c
int a = 0;
```
The output of the parser should be `(Stmt::Declare((ident, span_of_a), (expr, span_of_expr)), span_of_stmt)`

**Comment by wackbyte** [comment]
You can get this by using `map_with` on just the identifier by moving it with `ident` inside the `then`:
```rs
let stmt_declare = just(Token::Int)
        .then(ident.map_with(|ident, e| (ident, e.span())))
        .then(just(Token::Equals).ignore_then(expr()).or_not())
        .then_ignore(just(Token::Semicolon))
        .map_with(|((_ty, ident_and_span, expr_and_span), e| (Stmt::Declare(ident_and_span, expr_and_span), e.span()))
        .boxed();
```

**Comment by nouritsu** [comment]
Oh RIGHT! Thank you for the prompt help!
