### ISSUE TITLE
How to parse a repeated parser with recovery

### ISSUE THREAD

**Issue by geom3trik** [zesterer/chumsky#60]
Hello, I am trying to write a parser which can parse a series of items from a known set and I want to be able to skip over an item if it is wrong but still produce an error for this wrong item.

To be more specific I am trying to use chumsky to write a simplified css parser and I am stuck on the parsing of pseudoclass selectors. Let's say I have something like this:

":hover:activ:focus"

Here 'active' is spelt wrong so I want this to produce an error but for the parser to skip over this one and continue if possible. So far I have attempted to write a `psudoclass` parser using `choice` and `text::keyword` together, and then I have used `repeated` and `recover_with` but the recovery part does not seem to be working with `repeated`.

I wish I could be more specific but I'm still tyring to learn this crate so I'm not even sure of the correct terminology just yet. Any help or advice would be greatly appreciated. Thanks.

**Comment by geom3trik** [comment]
Argh, literally 2 minutes after posting this I realised that the `repeated` needs to go *after* the `recover_with` and not before. I'll leave this open for a little while in case I'm still doing something wrong and someone can tell me better but it *seems* to be working now.

**Comment by zesterer** [comment]
Yep, your approach is correct. As mentioned in the README, there is no silver bullet when it comes to error recovery, so experimenting with where and when you apply recovery patterns is a good idea!
