### ISSUE TITLE
`vars` gets not correctly truncated in example code

### ISSUE THREAD

**Issue by xtofs** [zesterer/chumsky#610]
in the example code, the lines
```
                vars.append(&mut args);
                let output = eval(body, vars, funcs);
                vars.truncate(vars.len() - args.len());
```

try to remove the number of arguments from the vars after previously adding them to vars. 

But the line `vars.append(&mut args)` empties args and therefore the length is zero, not removing anything. 

see [Vec::append](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append)

**Comment by zesterer** [comment]
Well caught, thanks! I've now fixed this.
