### ISSUE TITLE
Cannot use custom span type with Stream

### ISSUE THREAD

**Issue by jackdotink** [zesterer/chumsky#616]
In previous versions of chumsky using a custom span type was fairly painless and straightforward, but now it seems impossible because `Stream` uses `SimpleSpan` without any way to change this, and there is no other way to use user defined tokens as input.

**Comment by zesterer** [comment]
Check out the [`map_span`](https://docs.rs/chumsky/1.0.0-alpha.6/chumsky/input/trait.Input.html#method.map_span) method if you want to change the span of input types, it should do what you want.

As an additional point, although `Stream` in `1.0.0` is somewhat akin to the same type in `0.9`, chumsky is now a lot more general and can handle a far wider variety of input types. You might find that another type, like `&str` or `&[T]`, does a better job for you than `Stream`.

**Comment by jackdotink** [comment]
Ah I see, I didn't realize that `Input` was implemented for `&[T]`. I can definitely use that, thank you.

**Comment by zesterer** [comment]
You might find [this section](https://docs.rs/chumsky/1.0.0-alpha.6/chumsky/guide/_01_key_concepts/index.html#api-features) in the guide useful.
