### ISSUE TITLE
`skip_until` is consuming the `until`

### ISSUE THREAD

**Issue by mnbjhu** [zesterer/chumsky#619]
I would have imagined that the `skip_until` recovery should consume input while the `skip` parser yeilds a valid output and stop when the `until` parser is valid, but it shouldn't be consumed in the error. However it doesn't look like this is the case? (1.0.0-apha.6)

For instance, this will recover an `Statement::Error` but will then fail because a `Token::Newline` is expected next:
 ```rust
    stmt_parser()
        .recover_with(skip_until(
            none_of([Token::Newline]).ignored(),
            just(Token::Newline).ignored(),
            || Statement::Error,
        ))
        .separated_by(just(Token::Newline))
        .collect()
```
e.g. Suppose a valid statement is in the form 'let %ident% = %expr%' then the text:
```text
=
let some = "thing"
```
This won't recover an AST becuase the recovered error consumes [Token::Punct('='), Token::Newline] rather than the expected: [Token::Punct('=')] causing the `seperated_by` to fail.

I've had a look at `SkipUntil` in `recovery.rs` and making this change fixes the above:
```rust
fn recover<M: Mode, P: Parser<'a, I, O, E>>(
    &self,
    inp: &mut InputRef<'a, '_, I, E>,
    _parser: &P,
) -> PResult<M, O> {
    let alt = inp.errors.alt.take().expect("error but no alt?");
    loop {
        let before = inp.save();
        if let Ok(()) = self.until.go::<Check>(inp) {
            inp.rewind(before); // <----- Adding fixed the above
            inp.emit(inp.offset, alt.err);
            break Ok(M::bind(|| (self.fallback)()));
        }
        inp.rewind(before);

        if let Err(()) = self.skip.go::<Check>(inp) {
            inp.errors.alt = Some(alt);
            break Err(());
        }
    }
}
```

Is this a bug? Happy to raise a PR if so

**Comment by zesterer** [comment]
It's not a bug, but it is somewhat unexpected behaviour. This has been addressed in 1.0 (which I'd recommend moving to, 0.9 is effectively legacy at this point) with the inclusion of `not`, `rewind`, and `and_is`.

**Comment by mnbjhu** [comment]
This is in 1.0.0-apha.6...

**Comment by zesterer** [comment]
`skip_until` is only available in 0.9, which is now legacy.

**Comment by mnbjhu** [comment]
Can you explain what you mean? I've used versions: 1.0.0-alpha.0, 1.0.0-alpha.6, 1.0.0-alpha.7 and the main branch and `skip_until` is available in all of them? Am I missing something?

**Comment by zesterer** [comment]
Oh, that's my mistake in that case. It's been a while since I've touched error recovery, I should have double-checked first.

So the main use-case of `skip_until` is for imperative issues like C where, on encountering an error in a statement, can skip to just *after* the next semicolon and continue parsing.

In your case, that's clearly not so desirable, so I'd recommend using the much more flexible `via_parser` recovery strategy that allows you to specify a regular parser to act as your recovery strategy, like so: 

```rs
.recovery_with(via_parser(any().and_is(end.not()).repeated()))
```

(where `end` is whatever pattern you want to skip until, but not consume).

**Comment by mnbjhu** [comment]
Thank you for this! I've not had a chance to migrate to using it yet but will move over to this as soon as I can :)
