### ISSUE TITLE
"escape" parser in json example seems to be wrong

### ISSUE THREAD

**Issue by ShuiRuTian** [zesterer/chumsky#647]
If I get it correctly, `escape` parser is using `ignore` this indicates that the result will be ,ah, ignored. And the `string` is using `to_slice()` which will just use the origin string rather than mapped value. 

So, for string "\\\r", it will still be "\\\r", rather than "\r".

**Comment by zesterer** [comment]
Yes, the JSON parser in the example doesn't attempt to translate the string, only parse its structure: an attempt to translate the string would necessarily require character replacement and so on, which I consider to be beyond the scope of the example (and not necessarily useful for understanding how chumsky works).

**Comment by ShuiRuTian** [comment]
Does make sense, thanks for the answer!
