### ISSUE TITLE
wrong docs

### ISSUE THREAD

**Issue by sineptic** [zesterer/chumsky#652]
This work only for 1 blank line:
``` rust
.separated_by(blank_line())
```

This work as expected:
``` rust
.separated_by(blank_line().repeated().at_least(1))
```

---

doc string for `separated_by`:
/// Parse a pattern, separated by another, **any number of times**.

**Comment by zesterer** [comment]
What is `black_line`? `a.separated_by(b)` matches `abababa...`.

**Comment by sineptic** [comment]
> blank_line

it's my parser.

---

> `a.separated_by(b)` matches `abababa...`

> /// Parse a pattern, separated by another, **any number of times**.

`a.separated_by(b)` doesn't matches `abbbabbababa...`, but documentation sad `any number of times`

**Comment by CraftSpider** [comment]
It parses '(a pattern, separated by another) any number of times', not 'a pattern, seperated by (another, any number of times)'. This is supposed to be implied by the commas, is there a phrasing you would find clearer?

**Comment by sineptic** [comment]
mb `Parse items, separated by pattern.`

I can think about better explanation tomorrow.

**Comment by astrale-sharp** [comment]
i think this can be closed
