### ISSUE TITLE
Matching over struct/tuple enum items (using Logos)

### ISSUE THREAD

**Issue by ColinTimBarndt** [zesterer/chumsky#67]
Hello!

I wanted to combine the speed and simplicity of the Lexer generator [Logos] with the expressiveness of Chumsky and have run into an issue that I don't know how to resolve. Logos implements a function which returns a Lexer. This struct is an iterator over Tokens and has some additional functions like [`span`], which I need for error messages.

Is there any way for how I can access the token iterator in a way similar to `just(Token::Abc).map(|token| (lexer.span(), token))` and is it possible to match some `Token::Int(u32)`?

I can also convert the Lexer into an iterator over spanned Tokens using [`spanned`], but the problem of matching this tuple remains.
I am still learning this library and am sorry if this is something trivial.

[Logos]: https://github.com/maciejhirsz/logos
[`span`]: https://docs.rs/logos/latest/logos/struct.Lexer.html#method.span
[`spanned`]: https://docs.rs/logos/latest/logos/struct.Lexer.html#method.spanned

**Comment by zesterer** [comment]
Yes, this is exactly what [`map_with_span`](https://docs.rs/chumsky/latest/chumsky/trait.Parser.html#method.map_with_span) is for!

**Comment by ColinTimBarndt** [comment]
Ah, this function could be useful. Though I think that the span it provides references the tokens in the iterator and not the actual characters in the source file, as those are provided by the Logos Iterator.

I think it might be possible to use the spanned iterator and `filter_map` with a `match` inside to get pattern matching. This could be defined as a macro. But then the spans I get from Logos are from the specific token and not the span of the entire group of tokens that was parsed.

It would be neat if it was possible to generically override how spans work, because then I could integrate it with the spans provided by Logos.

**Comment by ColinTimBarndt** [comment]
Okay I think I figures it out now and came up with this "glue" that creates a Chumsky Stream from a Logos Lexer:

```rs
use std::iter::Map;

use chumsky::Stream;
use logos::{Lexer, Logos, Source, Span as LSpan, SpannedIter};

pub fn stream_of_lexer<'source, 'context, Token, Context>(
    lexer: Lexer<'source, Token>,
    context: Context,
) -> Stream<
    'source,
    Token,
    (Context, LSpan),
    Map<SpannedIter<'source, Token>, impl FnMut((Token, LSpan)) -> (Token, (Context, LSpan))>,
>
where
    Token: Logos<'source>,
    Context: Clone + 'static,
{
    let length = lexer.source().len();
    Stream::from_iter(
        (context.clone(), length..length + 1),
        lexer
            .spanned()
            .map(move |(token, span)| (token, (context.clone(), span))),
    )
}
```
This should work, though I haven't tested it yet.

**Comment by zesterer** [comment]
Yes, this seems like it should work. You can make use of `impl Iterator` in the return type to shorten the type signature even further!

**Comment by ColinTimBarndt** [comment]
> Yes, this seems like it should work. You can make use of `impl Iterator` in the return type to shorten the type signature even further!

True! This is my final code:
```rs
use chumsky::Stream;
use logos::{Lexer, Logos, Source, Span};

/// Converts a Logos lexer into a Chumsky stream
pub fn lexer_to_stream<'source, Token, Context>(
    lexer: Lexer<'source, Token>,
    context: Context,
) -> Stream<
    'source,
    Token,
    (Context, Span),
    impl Iterator<Item = (Token, (Context, Span))> + 'source,
>
where
    Token: Logos<'source> + 'source,
    Context: Clone + 'source
{
    let length = lexer.source().len();
    Stream::from_iter(
        (context.clone(), length..length + 1),
        lexer
            .spanned()
            .map(move |(token, span)| (token, (context.clone(), span))),
    )
}
```
