### ISSUE TITLE
Question: How to reduce symbol length?

### ISSUE THREAD

**Issue by eternal-flame-AD** [zesterer/chumsky#672]
Would appreciate some advice! I read the advice section in the docs and used boxing in each function and used choice for any >=3 or's. My compile time was okay (~10 seconds on an LTO'ed build, excl. dependencies) but I get giant symbol names which feels wasteful, for example this 29 byte function get a 30kb+ name, is the only option here stripping the binary?

Some naive grepping give me this histogram, I attached the full name of the longest symbol.
[symbol.txt](https://github.com/user-attachments/files/17072082/symbol.txt)
![image](https://github.com/user-attachments/assets/ae8cd385-7670-4ec0-a664-26b317ce5425)

Example of my code:

```rs
pub fn class<'tokens, 'src: 'tokens>() -> impl Parser<
    'tokens,
    ParserInput<'tokens, 'src>,
    Class<'src>,
    extra::Err<Rich<'tokens, Token<'src>, Span>>,
> + Clone {
    let tags = tags();

    let kw = just(Token::Keyword(Keyword::Class));

    let name = select! {
        Token::Ident(name) => name
    };

    let maybe_extends = just(Token::Keyword(Keyword::Extends))
        .ignore_then(path())
        .map(Some)
        .or(empty().map(|_| None));

    let body = just(Token::Ctrl('{'))
        .ignore_then(
            choice((
                var_decl()
                    .then_ignore(just(Token::Ctrl(';')))
                    .map(|vardecl| (Some(vardecl), None, None, None)),
                function().map(|func| (None, Some(func), None, None)),
                typedef().map(|typedef| (None, None, Some(typedef), None)),
                import().map(|import| (None, None, None, Some(import))),
            ))
            .repeated()
            .collect::<Vec<_>>(),
        )
        .then_ignore(just(Token::Ctrl('}')))
        .map(|body| {
            let mut members = Vec::new();
            let mut functions = Vec::new();
            let mut typedefs = Vec::new();
            let mut imports = Vec::new();
            for item in body {
                match item {
                    (Some(vardecl), None, None, None) => members.push(vardecl),
                    (None, Some(func), None, None) => functions.push(func),
                    (None, None, Some(typedef), None) => typedefs.push(typedef),
                    (None, None, None, Some(import)) => imports.push(import),
                    _ => unreachable!(),
                }
            }
            (members, functions, typedefs, imports)
        });

    tags.then_ignore(kw)
        .then(name)
        .then(maybe_extends)
        .then(body)
        .map(
            |(((tags, name), extends), (members, functions, typedefs, imports))| Class {
                tags,
                name,
                extends,
                typedefs,
                imports,
                members,
                functions,
            },
        )
}
```

**Comment by zesterer** [comment]
You can use `.boxed()` to switch to dynamic dispatch, which avoids large types. See [here](https://docs.rs/chumsky/1.0.0-alpha.7/chumsky/guide/_00_getting_started/index.html#compilation-times). Note that this doesn't always come with a performance hit: LLVM is often able to devirtualise the parsers and still statically knit them together. Sometimes, performance can even improve!

**Comment by eternal-flame-AD** [comment]
I only boxed expressions, statements and primitives like ifs, I will try boxing them all tomorrow and report back. Thanks

**Comment by eternal-flame-AD** [comment]
I boxed everything that is longer than 3 levels that doesn't require Send (lexer part) and got down to about 25 kb and the next largest is 14 kb. My build time got noticeably slower actually (I suppose LTO is trying to see through the box?) but it's still acceptable. I attached the new longest symbol here if there is anything to see but thanks for the help! If there is no more thing to do feel free to close this, thanks!
[symbol.txt](https://github.com/user-attachments/files/17080632/symbol.txt)
![image](https://github.com/user-attachments/assets/b41cf4ba-aa94-4216-837c-29ffd4c9506b)

**Comment by zesterer** [comment]
I think that's about all there is, sadly (at least: until rustc gets a bit smarter about symbol generation for nested types). The same thing happens with complex `Iterator` chains, although of course chumsky's pervasive use of the combinator pattern makes it much more common here.

**Comment by eternal-flame-AD** [comment]
Thanks for the help, and the project overall of course!

**Comment by tstack** [comment]
I'd kinda like to raise this issue again.  I'm using [PRQL](https://github.com/prql/prql/) in [my project](https://github.com/tstack/lnav/) and there is a symbol that is 750KB (753195 bytes to be exact).  There are several more symbols that are 300+KB  in size.  (I don't think I am mistaken here...)

Running `nm` on the static library produced in my build is 13MB.

```
$ nm src/third-party/prqlc-c/target/release/libprqlc_c.a | wc
   92093  254212 13859148
```

The first 200 characters of the really long symbol look like this:

```
__ZN4core3ptr753155drop_in_place$LT$chumsky..combinator..Repeated$LT$chumsky..combinator..Map$LT$chumsky..combinator..Then$LT$chumsky..combinator..OrNot$LT$chumsky..combinator..Label$LT$chumsky..comb
```

What is odd, though, is that the regular PRQL build doesn't seem to produce a symbol this large, it's just in my build.  I'm not sure why that is happening.

**Comment by eternal-flame-AD** [comment]
It really is hit or miss and a binary builds not having big symbols doesn't automatically mean library builds won't.

My understanding is while regular symbols are more optimized away as long as your parser involves anything that needs Drop it will need to generate a function to drop it. Unless you explicitly call `.boxed()` it will generate a very long type name for the type to drop.

My suspicion is these need-Drop closures wrapped in deep parsers are incredibly difficult to be reliably optimized out, maybe try forking PRQL, wrapping them in `.boxed()` before and after and try if you get better luck?

https://github.com/PRQL/prql/blob/4db3d30625de9cac7542e50b5e818642faba825a/prqlc/prqlc-parser/src/parser/expr.rs#L487-L494
