### ISSUE TITLE
Question: How to comfortably parse tokens with metadata

### ISSUE THREAD

**Issue by id-NaN** [zesterer/chumsky#675]
To allow me to show the exact position of issues I added start and end fields as indexes to the source into my tokens:

```rust
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum TokenValue<'a> {
    Assign,
    BitwiseAnd,
    ...
}

#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct Token<'a> {
    pub value: TokenValue<'a>,
    pub start: usize,
    pub end: usize,
}
``` 

When I do that i seemingly have to use either `select!` or `filter` for every single token when parsing those into an AST:

```rust
let assign = select! {
    Token {value: TokenValue::Identifier(ident), start, ..} => (ident, start)
}
.then(filter(Token::assign()))
.then(Expression::parser()).then(filter(Token::newline()).or(filter(Token::semicolon())))
.map(|((((ident, start), _), expr), Token { end, .. })| ASTNode {
    start,
    end: expr.end,
    value: Statement::Expression(ASTNode {
        start,
        end,
        value: Expression::Assign(ident, Box::new(expr)),
    }),
});
```

Is it possible to do this in a better way or is my whole approach flawed? If so, can you show me a better approach?

**Comment by zesterer** [comment]
The term you're looking for is 'span', and chumsky is designed from the start to have first-class support for them. Check out one of the many examples that demonstrate the use of spanned tokens.

**Comment by id-NaN** [comment]
i see what you mean now, tho the specific usage feels quite hard to decipher, as the examples integrate it with a lot of stuff at once and the documentation on this topic is currently quite sparse

**Comment by zesterer** [comment]
You can find more information [in the guide](https://docs.rs/chumsky/1.0.0-alpha.7/chumsky/guide/_01_key_concepts/index.html#the-span-trait) and [the various](https://docs.rs/chumsky/1.0.0-alpha.7/chumsky/trait.Parser.html#method.map_with) [doc examples](https://docs.rs/chumsky/1.0.0-alpha.7/chumsky/trait.Parser.html#method.to_span).
