### ISSUE TITLE
Implementing serde for more structs

### ISSUE THREAD

**Issue by cAttte** [zesterer/chumsky#695]
i see that chumsky already has a `serde` feature and a bunch of derived structs, so would you mind a PR that just adds the `#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]` bit to `ParseResult`, `Rich`, and any other structs if necessary?

**Comment by zesterer** [comment]
Hmm, what's the use-case there? Those types aren't really intended to be serialisable, their internals may change depending on the needs of the library.

**Comment by cAttte** [comment]
well, i just wanna send the results of my parser over to the frontend. am i doing it wrong?

**Comment by zesterer** [comment]
I think it would be better to use the various methods on `ParseResult` to pull the results out and then send them over. `ParseResult` is not intended as a general-purpose type, it really is tied to chumsky.

**Comment by cAttte** [comment]
hmm but i'd end up replicating the same structure of `{ output: T, errors: Vec<E> }` wouldn't i? output is obviously custom so that's no issue, but then i'd like to keep the structure of the error type (in my case Rich `{ span, reason, context }`), so i'd end up just writing a bunch of code to replicate this structure, when i could just serialize it directly?

**Comment by zesterer** [comment]
The problem with this is that serialisation necessarily results in the implementation details of the types becoming part of their API. This just isn't something we want to support, changing the internal representation of `Rich` or `ParseResult` should not require a semver bump. If you want to serialize your parser's output, it's your job to find a format that has the appropriate representation and stability guarantees that you require.

**Comment by cAttte** [comment]
yeah, i guess that makes sense. i also have no stakes in this anymore because the library i use for rpc requires another derive() on top of serde's so i'll just close this lol. thanks!

**Comment by zesterer** [comment]
Good luck!
