### ISSUE TITLE
`skip_until` and `skip_then_retry_until` always skip at least one token

### ISSUE THREAD

**Issue by jfecher** [zesterer/chumsky#78]
This can be an issue when parsing input like `let = expr` given a rust-like grammar:
```
let ident = ident().recover_with(skip_until([Equals, Semicolon], |_| Error));

just(Let)
    .then(ident)
    .then(just(Equals))
    .then(expression())
```
Ideally, this should still be able to parse input like the above, though since `skip_until` always skips at least one token, we miss the required `=` for the next rule. As far as I can tell, the only way around this is to remove the `skip_until` and make the whole ident rule optional which will throw out the error from it being missing entirely.

**Comment by zesterer** [comment]
Hi, thanks for pointing this out. I can see that this happens in `skip_until`, but I can't find a similar issue in `skip_then_retry_until`. Could you confirm that this is the case?

**Comment by zesterer** [comment]
I've hopefully improved this in 03e6d4, could you verify that this is fixed?

**Comment by jfecher** [comment]
I can't seem to reproduce it with `skip_then_retry_until` - I must have made an error when testing that originally. I can verify that `skip_until` is fixed, thank you!

**Comment by zesterer** [comment]
Great, thanks!
