### ISSUE TITLE
`repeated` followed by `at_least`

### ISSUE THREAD

**Issue by justinfargnoli** [zesterer/chumsky#85]
In the `nano_rust` example, when lexing operations `repeated` is followed by a call to `at_least`.

https://github.com/zesterer/chumsky/blob/64b10e2348efdea706dadbcad3f1a1ff899bd749/examples/nano_rust.rs#L62-L66

At first glance, this looks like a bug and should be fixed by using `repeated` exclusive or `at_least` depending on the semantics you want. But I'm new to `chumsky`, so I'm not sure. 

Is this in fact a bug? If not, what are the semantics of the parser that this will generate?

**Comment by zesterer** [comment]
`at_least` is not itself a parser combinator, but simply a method on the `Repeated` parser that modifies its behaviour. See [here](https://docs.rs/chumsky/latest/chumsky/combinator/struct.Repeated.html#method.at_least) for more information.
