### ISSUE TITLE
Incorrect JSON parser example

### ISSUE THREAD

**Issue by IWANABETHATGUY** [zesterer/chumsky#86]
I try to use the JSON parser under examples dir , mostly It works fine, but when I try to parse such snippet
```
{
 "test": "\u2222"
}
```
parser in example report a error, but actually this json snippet is valid according to the specification https://www.json.org/json-en.html

**Comment by bew** [comment]
In your example JSON, `\u` are 2 separate characters, so you should parse them separately, and not try to write `\u` in your rust code but `\\` and `u`.

note: I think it would have been better [as a discussion](https://github.com/zesterer/chumsky/discussions) rather than an issue.
